### ISSUE TITLE
IML fails on file system detection

### ISSUE THREAD

**Issue by kpoirier** [whamcloud/integrated-manager-for-lustre#1002]
**Description**
IML fails to detect file system after servers are added. I see failures on modprobe trying to load ldiskfs (not used here). I also see:
[19/Jun/2019:18:47:18] daemon WARNING get_nids: failed to open
[19/Jun/2019:18:47:28] daemon WARNING get_nids: failed to open
in the chroma-agent.log file on both MDS/OSS nodes.

**To Reproduce**
Using the web gui, detect file systems and choose the 4 servers. fails 

**Expected behavior**
I've used an older version of IML before with no issues, but we used ldiskfs on those systems. This system uses ZFS on MDS and OSS nodes. 

**Backtrace info**
Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 326, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 985, in run
    DetectScan(self).run(host_data)
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 67, in run
    if self.learn_primary_target(target):
  File "/usr/share/chroma-manager/chroma_core/lib/detection.py", line 169, in learn_primary_target
    raise NoNidsPresent("Host %s has no NIDS!" % tm.host)
NoNidsPresent: Host atheon-mdslcl1 has no NIDS!

### Version
What version of IML?  4.0.10.1
What Operating System?  CentOS
What Operating System version?  7.6.1810
Lustre version: lustre-2.12.0-1.el7.x86_64

**Comment by kpoirier** [comment]
Any Ideas on this issue? I'm stuck at this point.

**Comment by kpoirier** [comment]
Is more information needed to troubleshoot this?  Can someone please respond with any suggestions on how to get this working?

**Comment by johnsonw** [comment]
Hi @kpoirier, if you've deployed the agent nodes to the servers can you put them in debug mode? See https://whamcloud.github.io/Support/docs/support/common-troubleshooting-tips.html on how to do this. Once the nodes are running in debug mode, try detecting the fs again and look at the /var/log/chroma-agent{-console}.log on each node for any issues.

**Comment by kpoirier** [comment]
Looking at /usr/lib/python2.7/site-packages/chroma_agent/device_plugins/linux_network.py  I see this section:

 # Read active NIDs from /proc
        try:
            with open("/proc/sys/lnet/nis") as file:
                lines = file.readlines()
        except IOError:
            daemon_log.warning("get_nids: failed to open")
            return LinuxNetworkDevicePlugin.cached_results

On our version of lustre (2.12.0-1), the the /proc/sys/lnet  directory doesn't exist, thus cause lots of get_nids failed to open errors.  I'll put the nodes in debug mode and see if there are more clues.

**Comment by jgrund** [comment]
Hi @kpoirier, IML 4.0.10 is not compatible with Lustre 2.12. You will need to upgrade IML or reinstall it to version 5. Version 5 is compatible with Lustre 2.12
