### ISSUE TITLE
IML FS moves to unavailable state if one MDT is unmounted

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1023]
If Lustre is setup to have multiple MDTs, it seems that the filesystem should not move to the unavailable state unless MDT0 has been unmounted.

**Comment by utopiabound** [comment]
I'm not sure it's totally wrong.  Maybe an extra state of "degraded"?  Some directories or files will be unavailable if an MDT other than 0 is missing

**Comment by jgrund** [comment]
Yes, I think degraded would be fine iff MDT != 0 is unmounted. We can then rely on that state + available as usable states for scans.

**Comment by utopiabound** [comment]
Given the complexity of adding a state, I'm going to rescind my suggestion and just ignore non-zero MDTs for the "unavailable" state.
