### ISSUE TITLE
Implement stratagem configuration component

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1059]
Implement a component that allows for Configuration of stratagem scans.

In Scope:

- dropdown input for scan durations (support days / hours)
- Toggle dropdown input for Generate report duration (supports days / hours)
- Toggle dropdown input for Purge duration (supports days / hours)
- Save button to persist parameters to backend
- action-dropdown to move stratagem between the configured / unconfigured states.

**Comment by johnsonw** [comment]
- [ ] Update `StratagemConfigurationResource` to accept both Delete and Put. Delete will remove the entry entirely while Put will update the resource, putting it in either configured or unconfigured mode.
- [ ] Create the `Add Stratagem` button that will be displayed when a stratagem configuration row for a particular filesystem has not been created but all of the MDT's have the stratagem profile. This button will create a stratagem configuration for a filesystem in the unconfigured state.
- [ ] Remove `interval` from the list of required properties to be sent when configuring stratagem
- [ ] Add the entry point for the seed app in the filesystem detail page
- [ ] If the stratagem configuration row is created for a particular filesystem, the Stratagem Configuration GUI components should be displayed such that their values can be modified. A `Save` button will be provided if the state is unconfigured. Clicking this button will call the configure stratagem endpoint.
- [ ] If the stratagem configuration row is created for a particular filesystem and the state is configured, it should display two buttons: a `Delete` button to delete the entry and a `Save` button to save configuration changes.
- [ ] Use the alert indicator to display whether or not Stratagem is in the configured state. This will only show if there is a stratagem configuration entry in the database for the specified filesystem.
