### ISSUE TITLE
Corosync configures network incorrectly

### ISSUE THREAD

**Issue by JestersTear** [whamcloud/integrated-manager-for-lustre#1084]
In IML 5.0 the corosync network is configured incorrectly for an HA pair. The heartbeat interface is set as ring0_addr, which causes warnings with "pcs status":
 
WARNINGS: Corosync and pacemaker node names do not match (IPs used in setup?)

This also appears to cause issues with the filesystem mount on client nodes. the OST's of the lustre filesystem are not visible when running 'lfs df' command. 

The corosync.conf file:

totem {
    version: 2
    cluster_name: lustre-ha-cluster
    secauth: off
    transport: udp
    rrp_mode: passive
    token: 17000
    fail_recv_const: 10

    interface {
        ringnumber: 0
        bindnetaddr: 10.0.0.0
        mcastaddr: 226.94.0.1
        mcastport: 36121
    }

    interface {
        ringnumber: 1
        bindnetaddr: 172.21.61.0
        mcastaddr: 226.94.1.1
        mcastport: 36121
    }
}

nodelist {
    node {
        ring0_addr: 10.0.0.133
        nodeid: 1
    }
}

quorum {
    provider: corosync_votequorum
}

logging {
    to_logfile: yes
    logfile: /var/log/cluster/corosync.log
    to_syslog: yes
}

If this file is edited to make the 172.21 address the ring0_addr then the pcs WARNING message is not longer displayed, but IML warns that the server is 'offline' and lnet does not start on boot of the server.

We have several other lustre filesystems managed by IML version 4 where the corosync.conf files show the ring0_addr to be the primary address of the host (ie the 172.21 network) 

All servers are running Centos7.6

Any suggestions to the cause would be welcome
Thanks in advance

**Comment by jgrund** [comment]
Hi @JestersTear,

I'm assuming you've figured this out, but [ring 0 and ring 1 have switched](https://github.com/whamcloud/integrated-manager-for-lustre/issues/738) in IML 5, along with IML using [upstream RAs from Lustre and clusterlabs](https://github.com/whamcloud/iml-agent/issues/70).

When upgrading from IML 4, you need to run `chroma-agent convert_targets` on each storage server which is described more in this upgrade guide: https://whamcloud.github.io/Online-Help/docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.html. This will reverse the ring layout that was present in IML 4.x

**Comment by JestersTear** [comment]
Hi Joe,

Yes figured it out.

Thanks for checking.

Regards
Nick
