### ISSUE TITLE
When forgetting the filesystem in Monitored mode, also forget Stratagem

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1094]
When the user clicks the forget action on a monitored fs:

![Screen Shot 2019-07-27 at 4.34.00 PM.png](https://images.zenhubusercontent.com/5d25f5c19c24773a1026b5eb/ef081767-e8d4-4435-b686-672ffbe84c7b)

Is Stratagem is configured for the fs, it should have it's `UnconfigureStratagemJob` run as part of the fs removal. 

An open question is what should happen if someone attempts to remove the fs while a scan is occuring, but this can probably be handled in another issue.

**Comment by johnsonw** [comment]
```
chroma=> select * from chroma_core_stratagemconfiguration;
 id |       state_modified_at       |   state    | immutable_state | filesystem_id |  interval  | report_duration | purge_duration | not_deleted 
----+-------------------------------+------------+-----------------+---------------+------------+-----------------+----------------+-------------
  1 | 2019-07-30 14:08:54.268877+00 | configured | f               |             1 | 2592000000 |                 |                | t
```

![image.png](https://images.zenhubusercontent.com/5d262915495428167715b594/5770dac0-cc81-446f-bd16-fb1b53af5252)

![image.png](https://images.zenhubusercontent.com/5d262915495428167715b594/d24e339c-a5a7-4020-bedd-5b25f4a51608)

```
chroma=> select * from chroma_core_stratagemconfiguration;
 id |       state_modified_at       |  state  | immutable_state | filesystem_id |  interval  | report_duration | purge_duration | not_deleted 
----+-------------------------------+---------+-----------------+---------------+------------+-----------------+----------------+-------------
  1 | 2019-07-30 14:27:58.735253+00 | removed | f               |             1 | 2592000000 |                 |                | 

```
