### ISSUE TITLE
rmfid action does not remove directories

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1097]
The fid counts returned from stratagem consist of both files and directories. However the current non `llapi` fid removal (unsure if it's the same in the llapi version) only removes files and errors when it tries to remove a dir.

`Jul 24 15:28:05 c1.local iml-agent-daemon[17337]: [ERROR liblustreapi] Failed to remove [0x200001b71:0x2baf:0x0]: Os { code: 21, kind: Other, message: "Is a directory" }`

I'm not sure if a dir fid returned by stratagem means all the contents of that dir are also older than the specified time (seems reasonable). If so, we can just do `fs::remove_dir_all` for those fids.

Otherwise, we may need to be more surgical, and only remove the dir iff there are no files within it, and conversely check if the dir is empty after removing a file fid and possibly remove that dir.

N.B. this all may be moot if the llapi version of rmfid handles this differently and we should just use that approach.

**Comment by utopiabound** [comment]
tmpwatch doesn't remove directories by default either.

**Comment by jgrund** [comment]
Sure. I'm not positive what the correct fix is yet, but I think this will induce surprising behavior with the end user.

The inconsistency is that the reports generated by LiPE count both dirs and files, and the rmfid task only removes files. 

The surprising behavior I forsee is the reports never dipping below a certain threshold, as files are removed, but directories aren't.

**Comment by jgrund** [comment]
Looks like the correct fix is to update existing rules to filter out dir fids.

Something like: `!= type S_IFDIR`
