### ISSUE TITLE
Updating stratagem config should reconfigure the systemd timer

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1099]
When the Stratagem config is updated, the associated systemd timer and service should also be updated with a new interval and warn / purge durations if needed. Right now, the data is only being persisted to the db.

Create an `UpdateStratagemJob` that will update the systemd timer / service with the new values and reload it. The Command should be triggered on a `POST` to the stratagem endpoint.

In addition, add Rust cli support on the manager for updating.

**Comment by utopiabound** [comment]
![window](https://user-images.githubusercontent.com/2285913/62645877-1e975300-b91b-11e9-83c8-b9b2ef1669ea.png)
This is the command output after running configure add via CLI twice
