### ISSUE TITLE
Kick off the inode data fetch when the stratagem configuration is received.

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1106]
The inode table currently should kick off the fetch when the stratagem configuration is received.

**Comment by jgrund** [comment]
I'm not sure this is what we want to do. A Stratagem scan is actually a separate thing from a Stratagem config.

**Comment by johnsonw** [comment]
Basically my thinking is that when we first load the fs detail page there is no need to fetch inodes because stratagem may not be configured. At the moment we tell it to fetch regardless. I was thinking that when the page loads and stratagem is configured it would start the polling process to fetch the inode counts. But if it's not configured then it would not poll. So if someone deletes the configuration, it would send the cancel event to stop polling. Does that sound ok?

**Comment by jgrund** [comment]
> Basically my thinking is that when we first load the fs detail page there is no need to fetch inodes because stratagem may not be configured.

So, that's my point. A user can produce a stratagem scan without a configuration at all.

In other words metrics may be displayed regardless if there is a config.

**Comment by jgrund** [comment]
So, by only showing metrics when there is a config, we are enforcing an invariant that does not need to exist.

**Comment by johnsonw** [comment]
I see, I thought we only wanted to display the metrics if it was configured, but thinking about it more that makes sense. So if that's the case should we always show the inode table and the chart?

**Comment by jgrund** [comment]
In the case where the stratagem profiles are in place, yes

**Comment by johnsonw** [comment]
Ok, i'll close this issue then.

**Comment by jgrund** [comment]
I think we may want to refactor the configure panel a bit because it's a bit of a misnomer.

What we are really doing is setting a recurring scan timer...
