### ISSUE TITLE
Changing default server profile not reflected in WebUI

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1115]
Setting default profile via 

**To Reproduce**
1. `chroma-config profile default base_managed_patchless`
2. verify change in DB:
```
chroma=> select name, "default" from chroma_core_serverprofile;
          name          | default 
------------------------+---------
 default                | f
 robinhood_server       | f
 base_monitored         | f
 base_managed_ib_rh7    | f
 posix_copytool_worker  | f
 base_managed_rh7       | f
 base_managed_patchless | t

```
3. Add servers via WebUI
4. See error when selecting profile:
![screen](https://user-images.githubusercontent.com/2285913/62480108-fd98fb80-b77c-11e9-81b7-90fdc640aa76.png)

**Versions**
IML: python2-iml-manager-5.0.1-1.1564218668.el7.noarch
OS: el7.6

**Comment by jgrund** [comment]
Temp workaround is to refresh the page.

The base issue server_profiles are not pushed to the GUI on changes like other objects.

**Comment by jgrund** [comment]
Everything is pushed in GUI refresh.
