### ISSUE TITLE
Slow FID scanning

### ISSUE THREAD

**Issue by jamesanunez** [whamcloud/integrated-manager-for-lustre#1169]
We recently ran performance testing for IML FID scanning and think(hope?) the performance can be improved. 

Running with a single MDS/one MDT and using the command line ‘iml stratagem scan’ to purge and scan files, we saw the following performance:
files              scan time (sec.)   purge time (sec.)
100,000        41.5                     23.7
500,000        499.8                   74.1
1,000,000     1,792.9               1,568.8

We are using IML 0.1.0.

**Comment by jgrund** [comment]
I was able to get a good speedup. 1,785,000 fids written in ~ 6 minutes.

To write almost 2x as many fids took ~ 20% of the time.

**Comment by jgrund** [comment]
new results after landing #1170 and retesting:

| num fids  | report time (seconds) | purge time (seconds) |
|-----------|-----------------------|----------------------|
| 100,000   | 27.8                  | 6.8                  |
| 500,000   | 111                   | 9.9                  |
| 1,000,000 | 217.5                 | 15.2                 |
