### ISSUE TITLE
Ensure manage_corosync2 action plugins / corosync device plugin works with existing HA

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1186]
Ensure manage_corosync2 action plugins / corosync device plugin works with existing HA

**Comment by utopiabound** [comment]
**Existing functions**
`chroma_agent/action_plugins/managed_pacemaker.py`:

Function | Working
------|------
start_pacemaker | Y
stop_pacemaker| Y
enable_pacemaker| Y
configure_pacemaker| N
unconfigure_pacemaker| Y
configure_fencing | ? - Only `fence_chroma`
unconfigure_fencing| ? - Only `fence_chroma`
set_node_standby| Y?
set_node_online| Y?
delete_node| Y?

`chroma_agent/action_plugins/managed_corosync2.py`:

Function | Working
------|------
start_corosync2 | Y
stop_corosync2 | Y
configure_corosync2_stage_1 | N - conflicts with existing HA
configure_corosync2_stage_2 | N - conflicts with existing HA
change_mcast_port | Possibly - depends on how corosync was originally setup
unconfigure_corosync2 | Y?

`chroma_agent/action_plugins/managed_corosync_common.py`:

Function | Working
------|------
get_corosync_autoconfig | Possibly, but unlikely
configure_network | Possibly
