### ISSUE TITLE
Update styles

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1196]
Refresh styling in IML

Bonus points for using https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme which will default to the current os light / dark theme.

**Comment by jgrund** [comment]
![Screen Shot 2019-10-10 at 9 32 25 AM](https://user-images.githubusercontent.com/458717/66573581-e4c41200-eb40-11e9-8a73-3eb39c116299.png)

**Comment by johnsonw** [comment]
Looks good 👍
