### ISSUE TITLE
IML 5.1 Manual Testing

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1217]
- [x] IML 5.1 managed ldiskfs
- [x] IML 5.1 managed ZFS
- [x] IML 5.1 monitored ldiskfs
- [x] IML 5.1 monitored ZFS
- [ ] IML Upgrade testing from 4.0.10.2 managed ldiskfs to 5.1
- [x] IML Upgrade testing from 5.0.x managed ldiskfs to 5.1

#  IML 5.1 managed ldiskfs

## Manager Installation
Follow the steps under https://wiki.whamcloud.com/display/DOC/IML+Manual+Testing for managed ldiskfs testing.

1. Install IML 5.1 from copr:
```
vagrant provision adm --provision-with install-iml-5.1
```
1. Follow the steps to create a managed ldiskfs filesystem with power control setup (https://wiki.whamcloud.com/display/DOC/Managed+Ldiskfs).

Creating the Filesystem: 

**expected:**
I was able to create a filesystem in IML@5.1, write data to the client and see the data in the charts on the dashboard.

**actual:**

Worked as expected

## Failover

**expected:**
After halting OSS1 each of the targets on oss1 should have failed over to oss2. When oss1 was brought back online, I was able to fail back each of the targets that failed over and all alerts were removed.

**actual:**

Worked as expected

iml-diagnostics for:
adm: [sosreport-adm-2019-10-10-itbtzxr.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3717709/sosreport-adm-2019-10-10-itbtzxr.tar.xz.zip)
mds1: [sosreport-mds1-2019-10-10-uaoslmw.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3717710/sosreport-mds1-2019-10-10-uaoslmw.tar.xz.zip)
mds2: [sosreport-mds2-2019-10-10-upnnjqy.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3717711/sosreport-mds2-2019-10-10-upnnjqy.tar.xz.zip)
oss1: [sosreport-oss1-2019-10-10-fduzgbq.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3717712/sosreport-oss1-2019-10-10-fduzgbq.tar.xz.zip)
oss2: [sosreport-oss2-2019-10-10-pbmwiyb.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3717713/sosreport-oss2-2019-10-10-pbmwiyb.tar.xz.zip)

# IML 5.1 managed zfs

## Manager Installation
Follow the steps under https://wiki.whamcloud.com/display/DOC/IML+Manual+Testing for managed zfs testing.

1. Install IML 5.1 from copr:
```
vagrant provision adm --provision-with install-iml-5.1
```
1. Follow the steps to create a managed zfs filesystem with power control setup (https://wiki.whamcloud.com/display/DOC/Managed+Ldiskfs).

Creating the Filesystem: 

**expected:**
I was able to create a filesystem in IML@5.1, write data to the client and see the data in the charts on the dashboard.

**actual:**

Worked as expected

## Failover

**expected:**
After halting OSS1 each of the targets on oss1 should have failed over to oss2. When oss1 was brought back online, I was able to fail back each of the targets that failed over and all alerts were removed.

**actual:**

Worked as expected

iml-diagnostics for:

- adm: [sosreport-adm-2019-10-04-grmxrqp.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3691906/sosreport-adm-2019-10-04-grmxrqp.tar.xz.zip)
- mds1: [sosreport-mds1-2019-10-04-qpkeyxi.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3691914/sosreport-mds1-2019-10-04-qpkeyxi.tar.xz.zip)
- mds2: [sosreport-mds2-2019-10-04-emgiwjh.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3691917/sosreport-mds2-2019-10-04-emgiwjh.tar.xz.zip)
- oss1: [sosreport-oss1-2019-10-04-kbcdqsk.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3691909/sosreport-oss1-2019-10-04-kbcdqsk.tar.xz.zip)
- oss2: [sosreport-oss2-2019-10-04-xiiykvy.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3691912/sosreport-oss2-2019-10-04-xiiykvy.tar.xz.zip)

---

# IML 5.1 monitored ldiskfs

## Manager Installation
Follow the steps under https://wiki.whamcloud.com/display/DOC/IML+Manual+Testing for monitored ldiskfs testing.

1. Install IML 5.1 from copr:
```
vagrant provision adm --provision-with install-iml-5.1
```
1. Follow the steps to create a monitored ldiskfs filesystem with power control setup (https://wiki.whamcloud.com/display/DOC/Managed+Ldiskfs).

Creating the Filesystem: 

**expected:**
I was able to create a filesystem in IML@5.1, write data to the client and see the data in the charts on the dashboard.

**actual:**

Works as expected
...

iml-diagnostics for:
adm: [sosreport-adm-monitored-ldisk-2019-10-10-qdlswrp.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714307/sosreport-adm-monitored-ldisk-2019-10-10-qdlswrp.tar.xz.zip)
mds1: [sosreport-mds1-2019-10-10-mfmlhqw.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714309/sosreport-mds1-2019-10-10-mfmlhqw.tar.xz.zip)
mds2: [sosreport-mds2-2019-10-10-oreqofj.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714315/sosreport-mds2-2019-10-10-oreqofj.tar.xz.zip)
oss1: [sosreport-oss1-2019-10-10-hmtozgu.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714317/sosreport-oss1-2019-10-10-hmtozgu.tar.xz.zip)
oss2: [sosreport-oss2-2019-10-10-cduhbva.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714325/sosreport-oss2-2019-10-10-cduhbva.tar.xz.zip)

---

# IML 5.1 monitored zfs

## Manager Installation
Follow the steps under https://wiki.whamcloud.com/display/DOC/IML+Manual+Testing for monitored ldiskfs testing.

1. Install IML 5.1 from copr:
```
vagrant provision adm --provision-with install-iml-5.1
```
1. Follow the steps to create a monitored zfs filesystem with power control setup (https://wiki.whamcloud.com/display/DOC/Managed+Ldiskfs).

Creating the Filesystem: 

**expected:**
I was able to create a filesystem in IML@5.1, write data to the client and see the data in the charts on the dashboard.

**actual:**

Works as expected.

iml-diagnostics for:
adm: [sosreport-adm-2019-10-10-owepluo.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714730/sosreport-adm-2019-10-10-owepluo.tar.xz.zip)
mds1: [sosreport-mds1-2019-10-10-hltfkgk.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714731/sosreport-mds1-2019-10-10-hltfkgk.tar.xz.zip)
mds2: [sosreport-mds2-2019-10-10-icrlrux.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714732/sosreport-mds2-2019-10-10-icrlrux.tar.xz.zip)
oss1: [sosreport-oss1-2019-10-10-alxkdch.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714733/sosreport-oss1-2019-10-10-alxkdch.tar.xz.zip)
oss2: [sosreport-oss2-2019-10-10-fnraqgh.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3714734/sosreport-oss2-2019-10-10-fnraqgh.tar.xz.zip)

---

# IML Upgrade testing from 5.0.x managed ldiskfs to 5.1

## Manager Installation
Follow the steps under https://wiki.whamcloud.com/display/DOC/Managed+Mode+Upgrade+Testing for managed ldiskfs upgrade testing.

1. Install IML 5.0.x from copr:
```
vagrant provision adm --provision-with install-iml-5
```
1. Follow the steps to create a managed ldiskfs filesystem with power control setup (https://wiki.whamcloud.com/display/DOC/Managed+Ldiskfs).
1. Download the 5.1 release from https://github.com/whamcloud/integrated-manager-for-lustre/releases/tag/v5.1.0 and move it up to the adm node.
1. Install the new 5.1 release

Manager Upgrade: 

**expected:**
After setting up a filesystem in IML 5.0.x and creating a filesystem, IML was updated to IML@5.1.0 without any issues.

**actual:**
...

## Server Upgrade

**expected:**
Each of the servers upgraded without any issues.

**actual:**

## Failover

**expected:**
After halting OSS1 each of the targets on oss1 should have failed over to oss2. When oss1 was brought back online, I was able to fail back each of the targets that failed over and all alerts were removed.

**actual:**
...

iml-diagnostics for:
adm:
mds1:
mds2:
oss1:
oss2:

---

# IML Upgrade testing from 4.0.10.2 managed ldiskfs to 5.1

## Manager Installation

Using https://wiki.whamcloud.com/display/DOC/IML+Manual+Testing as a guide, setup IML@4.0.10.2, add servers, setup power control, create a filesystem, connect a client and add some files to generate metrics on the dashboard.

1. Install IML 4.0.10.x from copr:
```
vagrant provision adm --provision-with install-iml-4.0.10
```
1. Follow the steps to create a managed ldiskfs filesystem with power control setup (https://wiki.whamcloud.com/display/DOC/Managed+Ldiskfs).
1. Download the 5.1 release from https://github.com/whamcloud/integrated-manager-for-lustre/releases/tag/v5.1.0 and move it up to the adm node.
1. Follow the upgrade instructions at: https://whamcloud.github.io/Online-Help/docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.html and install IML@5.1 as described.

Manager Upgrade: 

**expected:**
After setting up a filesystem in IML 4.0.10.2 and creating a filesystem, IML was updated to IML@5.1.0 without any issues.

**actual:**
...

## Server Upgrade
Using the same document as a guide (https://whamcloud.github.io/Online-Help/docs/Upgrade_Guide/upgrade_iml-4.0-el7_to_iml-5.0-el7.html), upgrade each of the server nodes.

**expected:**
Each of the servers upgraded without any issues.

**actual:**

## Failover

**expected:**
After halting OSS1 each of the targets on oss1 should have failed over to oss2. When oss1 was brought back online, I was able to fail back each of the targets that failed over and all alerts were removed.

**actual:**
...

iml-diagnostics for:
adm:
mds1:
mds2:
oss1:
oss2:

**Comment by bm13kk** [comment]
i have issue with 4.0.10
web GUI not working for me - i have endless loop
 iml-diagnostics
```
sosreport (version 3.7)

This command will collect diagnostic and configuration information from
this CentOS Linux system and installed applications.

An archive containing the collected information will be generated in
/var/tmp/sos.xT0nV5 and may be provided to a CentOS support
representative.

Any information provided to CentOS will be treated in accordance with
the published support policies at:

  https://wiki.centos.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.


 Setting up archive ...
 Setting up plugins ...
 Running plugins. Please wait ...

  Starting 1/13  block           [Running: block]
  Starting 3/13  filesys         [Running: block filesys]
  Starting 2/13  corosync        [Running: block filesys corosync]
  Starting 4/13  iml             [Running: block filesys corosync iml]
  Starting 5/13  kernel          [Running: block filesys iml kernel]
  Starting 6/13  logs            [Running: filesys iml kernel logs]
  Starting 7/13  memory          [Running: iml kernel logs memory]
  Starting 8/13  multipath       [Running: iml kernel memory multipath]
  Starting 9/13  pacemaker       [Running: iml kernel pacemaker]
  Starting 10/13 pci             [Running: iml kernel pacemaker pci]
  Starting 11/13 processor       [Running: iml kernel pacemaker processor]
  Starting 12/13 system          [Running: iml kernel processor system]
  Finishing plugins              [Running: iml processor system]
  Starting 13/13 yum             [Running: iml processor system yum]
  Finishing plugins              [Running: iml processor yum]
  Finishing plugins              [Running: iml processor]
  Finishing plugins              [Running: iml]

  Finished running plugins

Creating compressed archive...

Your sosreport has been generated and saved in:
  /var/tmp/sosreport-adm-2019-09-25-wcseafe.tar.xz

The checksum is: f96c6f17a7980c579868c775b6d3d152

Please send this file to your support representative.
```

**Comment by bm13kk** [comment]
in 4010 in web console
warning `Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.`
and many errors `Content Security Policy: The page’s settings blocked the loading of a resource at data:application/font-woff2;charset=utf-… (“font-src”).`

**Comment by bm13kk** [comment]
add servers
`mds[1,2], oss[1,2]`

**Comment by bm13kk** [comment]
IML 5.1 managed ldiskfs - installation - check

**Comment by jgrund** [comment]
IML 5.1 Managed ZFS testing completed without issues.

**Comment by jgrund** [comment]
Closing in favor of #1316
