### ISSUE TITLE
RPM lock issue

### ISSUE THREAD

**Issue by bm13kk** [whamcloud/integrated-manager-for-lustre#1228]
**Describe the bug**
In some cases, node can zombify rpm process. By lock it ducring install and not relese it properrly

```
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  94 M RSS (1.3 GB VSZ)
    Started: Mon Sep 30 17:19:46 2019 - 36:48 ago
    State  : Sleeping, pid: 28501
```

**To Reproduce**
1. Create new clean oss node
2. Start installing a server on it
3. Cancel installation during 4\5 step `Installing packages on oss2.local`
4. Start installation again

**Expected behavior**
Installation finish without issue in time

**Screenshots**
Find `rpm` process `ps aux | grep -i rpm`
Check its output ` sudo tail -F /proc/<pid>/fd/{0,1,2}`

### Version
What version of IML - 5.1
What Operating System - CoreOs
What Operating System version - 7.6

**Comment by bm13kk** [comment]
manual fix - kill process AND `sudo  yum-complete-transaction`

**Comment by jgrund** [comment]
Fixed, issue was due to use of versionlock after a non-matching dep had been installed.
