### ISSUE TITLE
refactor code using repo names

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#123]
As an example, in [find_deps.py](https://github.com/intel-hpdd/intel-manager-for-lustre/blob/477de244a34ed7c437cf50af27997223ca180e4d/chroma-bundles/include/find_deps.py) we have this code:

```
    def disable_all_repos(self):
        for repo in self.yb.repos.findRepos("*"):
            # these are hardcoded to the distro defaults and our own
            # infrastructure right now
            # these probably need to be externally specified
            if repo.id != "base" and repo.id != "core-0" and \
               repo.id != "updates" and repo.id != "updates-centos7.3-x86_64" and \
               repo.id != "extras" and \
               repo.id != "addon-epel7-x86_64" and repo.id != "epel" and \
               repo.id != "copr-be.cloud.fedoraproject.org_results_managerforlustre_manager-for-lustre_epel-7-x86_64_":
                repo.disable()
```

Using repository names here is obviously not very portable.  We need to find some way of identifying the repositories we want without using names.

There are probably other occurrences of using non-portable repository names in the code that need to be fixed likewise.

**Comment by jgrund** [comment]
`find_deps.py` no longer exists.
