### ISSUE TITLE
Available updates button disabled

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1237]
The available updates button remains disabled in an upgrade to 5.1. This is due to warp-drive not picking up changes for the computed property `member_of_active_filesystem` (which is derived mostly from the fs table). It seems like the most straightforward way to solve this is to check for server fs membership in the GUI by joining the data sets together.

**Comment by johnsonw** [comment]
I have a working implementation for this. I'm in the process of writing some tests and checking a couple of other test cases manually. The video below shows an example of the `Install Updates` button working as expected.

**Comment by johnsonw** [comment]
![update-install-updates-button](https://user-images.githubusercontent.com/1100657/66841092-2684fc00-ef37-11e9-8778-4fceda798e51.gif)

**Comment by johnsonw** [comment]
Another update showing the button changes in real time when the filesystem is started and stopped in another session.

**Comment by johnsonw** [comment]
![multi-session-button-change](https://user-images.githubusercontent.com/1100657/66861494-1aac3080-ef5d-11e9-986a-a414eab9d700.gif)
