### ISSUE TITLE
Agent - postman

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1239]
Maps UnixDomainSocket to mailbox on IML

* Create & listen to sockets in list
* Config: `/etc/iml/postman.conf`
Example Config:
```
<MAILBOX_NAME_0>
<MAILBOX_NAME_1>
...
```
These will map to socket: `/var/run/iml/postman-<MAILBOX_NAME_0>.sock`
To mailbox mailbox of same name.

*IML Agent Daemon*
* `on_message` - add/delete a mailbox-socket message, and start/stop new/old listeners
* `start_session` - start up listeners in config

**Comment by jgrund** [comment]
1. Need an agent-daemon per-server that streams and aggregates per-OST. 
1. Need to scan mounted OSTs and add / remove lpurge as needed.
1. Stream fids from each daemon to mailbox.
1. Client daemon that reads from mailbox and does the purge.
