### ISSUE TITLE
Configure / Display OST Pools

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1241]
Allow for the configuration of OST pools.
Show existing pools.

**Comment by utopiabound** [comment]
I can work through the backend portion of this.

**Comment by jgrund** [comment]
One thing to note is that any API layer joining between targets and pools should only use resource URIs and basically mirror the database tables. 

This is important so warp-drive can be notified of any LISTEN / NOTIFY updates.

**Comment by jgrund** [comment]
Closing in favor of #1460
