### ISSUE TITLE
Create manager cli to update IML agent repo

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1249]
Create a cli that will run `UpdateYumFileStep` for hosts.

**Comment by johnsonw** [comment]
I've tested upgrading both 4.0..10 to 5.1 and 5.0 to 5.1 using the backported cli. From my testing, it looks like we need to restart the update service after the repo file has been updated. Attached are gif's showing before the service gets restarted and after it is restarted.

**Comment by johnsonw** [comment]
Before service is restarted:
![updates-available-1](https://user-images.githubusercontent.com/1100657/67543418-4a76d900-f6bf-11e9-8c89-0d082f63b8da.gif)

**Comment by johnsonw** [comment]
After restarting the service:
![update-repo-restart-service](https://user-images.githubusercontent.com/1100657/67543463-80b45880-f6bf-11e9-97ae-e2fb3bfe39de.gif)
