### ISSUE TITLE
Updates_ready will always be false when upgrading a monitored filesystem from 4.0.10.x to 5.1

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1264]
The chroma-agent will poll package information from yum on each of the server nodes and send a blob of data over a session to the manager. This message is picked up and processed in https://github.com/whamcloud/integrated-manager-for-lustre/blob/b5.1/chroma_core/services/lustre_audit/update_scan.py#L108. The problem is that it looks at the packages associated with a profile:
```
for package in self.host.server_profile.serverprofilepackage_set.all():
```

However, there are no packages associated with a monitored profile, which means it will never enter the for loop and thus the package data is never processed. This means that the server nodes will continue to run a previous version of the agent and the "Updates Available" button will remain disabled.

**Comment by utopiabound** [comment]
It looks like `self.host.server_profile.serverprofilepackage_set.all()` should just be `self.host.server_profile.packages`
Should we define a set of "base" packages in ServerProfile (i.e. python2-iml-agent, rust-iml-agent) that we can check?  currently that list is defined in two places chroma_agent_comms/views.py::setup() and chroma_core/models/host.py::UpdateJob.get_steps()
