### ISSUE TITLE
client_count bytes_{free,total}, files_{free,total} do not live-update

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1285]
https://github.com/whamcloud/integrated-manager-for-lustre/blob/85150ae1292b78a810c73a89c64fca16ed7ba2e6/chroma_api/filesystem.py#L288-L292

These properties are computed from metrics and will not always update from warp-drive as there is not a direct correspondence to the chroma_coremanagedfilesystem table.

We should poll these stats when needed (once per 10s?) directly from the /metrics endpoint.

**Comment by johnsonw** [comment]
Polling will take place on the following pages:
1. Dashboard
2. Filesystem
3. Filesystem detail

It will call the metrics endpoint every 10 seconds.
