### ISSUE TITLE
Data race between CACHE_INITIAL_DATA and warp drive

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1375]
**Describe the bug**
When creating a filesystem there are times where the data being passed in is a map instead of a string. This is due to a race between the data coming from warp drive and CACHE_INITIAL_DATA. The data should be consistent coming from both ends.

**To Reproduce**
1. Create a filesystem
2. You may or may not get the error in the browser console

**Expected behavior**
The data should be in the same format regardless of whether or not it comes from CACHE_INITIAL_DATA or warp drive. It should not cause an error in the console.

### Version
What version of IML? 5.1
What Operating System? OS X
What Operating System version? Catalina

**Comment by jgrund** [comment]
Fixed as part of new GUI rollout.
