### ISSUE TITLE
`create_lamigo_service` plugin

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1379]
Create a `create_lamigo_service`  action plugin that does the following:

1. Creates a unit in `/etc/systemd/system/` named `lamigo-<FS_NAME>-<MDT_NAME>.service` that runs: `lamigo -a <MIN_AGE> -m <FS_NAME>-<MDT_NAME> -u <CHANGELOG_USER_NAME> -t <COLD_POOL> -s <HOT_POOL> <MNT_PNT>`.

**Comment by utopiabound** [comment]
A start action should be to mount the filesystem if it is not mounted already.

**Comment by utopiabound** [comment]
Mount of lustre client can be it's own service start, I'll take care of then in [EX-741](https://jira.whamcloud.com/browse/EX-741)

**Comment by jgrund** [comment]
@utopiabound I.E. systemd mount unit?
