### ISSUE TITLE
create_ltuer_conf plugin

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1382]
create a `create_ltuer_conf` plugin that does the following:

1. (Client) Writes the following conf out to `/etc/iml/ltuer.conf` that contains:

    ```
     mailbox=<MAILBOX_PATH>
     fs_name=<FS_NAME>
     cold_pool=<COLD_POOL_NAME>
    ```

**Comment by mkpankov** [comment]
Where do I get the data from (`MAILBOX_PATH`, `FS_NAME`, `COLD_POOL_NAME`)?

**Comment by jgrund** [comment]
They will be input parameters to the action plugin.

`fn create_ltuer_conf((mailbox_path, fs_name, cold_pool):(String, String, String)) {...}`
