### ISSUE TITLE
Implement line based reading from mailbox

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1396]
Implement line based reading from the mailbox.

A rough idea of how it should work:

1. Client sends a GET to the mailbox with a header indicating how many lines it wishes to read.
1. mailbox service checks if the corresponding mailbox has that many lines available for reading, if so it removes those lines and sends them to the client.

This should all be handled in a single loop (or locking the mailbox file) to avoid races between multiple clients requesting lines in parallel.

**Comment by ip1981** [comment]
> Client sends a GET
> it removes those lines and sends them to the client.

I think GET is not quite appropriate for that. Even if not a GET, removing content before ensuring client has read it might be fragile. Maybe two requests: one GET (read-only) and DELETE.

Some more questions: what's in the mailbox - text, random binary data? How long can the lines be?

**Comment by jgrund** [comment]
> Maybe two requests: one GET (read-only) and DELETE.

I think that would be fine.

> what's in the mailbox - text, random binary data?

Text

> How long can the lines be?

Infinite

> P. S. Related to #1398?

Yes and no. #1398 will use the line based reading (so multiple clients can process in parallel), but this feature is standalone.

**Comment by jgrund** [comment]
Closing due to moving tasks into database.
