### ISSUE TITLE
Notifications are shown to non-authenticated user

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1400]
Notifications are shown to a non-authenticated user.

**To Reproduce**
1. Provision a cluster in Vagrant
1. `vagrant halt`
2. `vagrant up`
3. Load web UI and be ready to quickly refresh it after next 2 steps. Don't log in, log out if you're logged in
3. `sudo systemctl restart rabbitmq-server.service`
3. `sudo chroma-config restart`
3. Refresh web UI - most likely it will show couple of errors about various hosts being offline, which quickly go away

In my case I have a BMC issue so that warning is shown persistently.

**Expected behavior**
Notifications potentially expose details of system configuration and probably shouldn't be shown to non-authenticated users.

**Screenshots**
![image](https://user-images.githubusercontent.com/393741/70698963-72ef7c80-1cd9-11ea-9e89-9f07b39e102e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 71

### Version
What version of IML? 5.1-devel
What Operating System? CentOS
What Operating System version? 7.x

**Comment by mkpankov** [comment]
Actually one might consider this 2 separate issues. One is showing the problems in "Status" to non-authenticated users, another is showing notifications with these problems to non-authenticated users.

**Comment by jgrund** [comment]
This is tunable on a per-site basis. If a site is concerned with not showing any information to unauthenticated users they can set `ALLOW_ANONYMOUS_READ=False`. This will force login before displaying any further info.

Ref: https://whamcloud.github.io/Online-Help/docs/Install_Guide/ig_ch_05_install.html

**Comment by mkpankov** [comment]
I see, thanks!
