### ISSUE TITLE
Implement --prompt / --force flags for adding new servers

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1421]
Servers can be added via the iml CLI with a command like:

```
iml server add --hosts mds[1,2].local,oss[1,2].local --profile base_managed_patchless
```

However, if the command fails, the user has no recourse and must deploy servers via the GUI instead.
Instead of that, we can add two new mutually exclusive flags to the `iml server` command.

`--prompt`

This flag will ask for confirmation to continue deployment if a command returns with an error during server deployment. The user must type `y` to continue, or `n` to abort. The command failure should be displayed so the user know what they are agreeing to.

`--force`

This flag will move to the next step in the deployment process regardless of the Command failure. Even though the command has failed, we should still print what the error was before continuing.

The code for the server CLI lives here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/25587229ee99e419fd8083469ab78436641c773c/iml-manager-cli/src/server.rs

**Comment by Basil22** [comment]
Build failed:

```
   Compiling termion v1.5.4
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\Basil\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.4\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
```

Adding ```sys = "*"``` to Cargo.toml doesn't help.

If this is the known trouble, please tell the solution.

**Comment by Basil22** [comment]
Which command errors should be ignored?

I see at least four points of potential failure:
- preflight checks
- wait_for_cmds(commands).await? after "agents..."
- wait_till_agent_starts(&hosts, &profile.name).await?;
- wait_for_cmds(commands).await? after "host profiles..."

**Comment by mkpankov** [comment]
> Is it possible to run server cli under Windows?

I don't think so.

> If not, can you give me an access to Unix machine where I can build and run that cli?

Local Linux VM would be much easier I think.

**Comment by jgrund** [comment]
If you just want to build locally, you can run the following command inside the integrated-manager-for-lustre dir (with docker installed / running):

`docker run -it -e SPEC=“rust-iml.spec” -e LOCAL_ONLY=“True” -e CARGO_HOME=/build/.cargo -v $(pwd):/build:rw imlteam/copr-rust:stable`

This will build / produce an RPM within the `_topdir` directory structure.

In order to test your changes you can use https://github.com/whamcloud/Vagrantfiles (this brings up a cluster of VMs, which can be used to build as well).

**Comment by mkpankov** [comment]
As Docker itself can be difficult on Windows, I recommend installing CentOS 7 or Fedora 31 on VirtualBox or VMWare and developing there. Then docker can be run from inside the VM to check the full build if you want that, although the same happens in PR CI so you'll be able to see build failures anyway.

So developing and running CLI in Linux VM is probably enough for the task.

**Comment by Basil22** [comment]
Good, thank you. I have built it under Windows by commenting termion lines, so build is not a problem.

But I still need a guidance which error should be ignored. 

The issue tells "_move to the next step in the deployment process regardless of the Command failure_". What is the Command - the whole command "iml server add"? Some part of add command, like
preflight checks
wait_for_cmds(commands).await? after "agents..."
wait_till_agent_starts(&hosts, &profile.name).await?;
wait_for_cmds(commands).await? after "host profiles..."
or something else?

**Comment by jgrund** [comment]
@Basil22 There are two spots:

1. If any of the preflight checks have failed:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/00ec637c3c54de10d26700e13fab5bc2ad7350a9/iml-manager-cli/src/server.rs#L302-L306

2. if any of the host profiles are invalid (this is currently being filtered out):

https://github.com/whamcloud/integrated-manager-for-lustre/blob/00ec637c3c54de10d26700e13fab5bc2ad7350a9/iml-manager-cli/src/server.rs#L349-L363

I also have a patch in flight that removes termion here:

https://github.com/whamcloud/integrated-manager-for-lustre/pull/1426

I think this should allow you to `cargo check` the `iml-manager-cli` crate individually if you base your changes on it.

**Comment by Basil22** [comment]
Great! Thank you for the patch. CLI compiles under Windows now. And also thanks for spots, I'll continue work on issue.
