### ISSUE TITLE
Put docker-compose.yml file in a package

### ISSUE THREAD

**Issue by mdiep25** [whamcloud/integrated-manager-for-lustre#1457]
Currently we have to download the docker compose file to run setup. It would be nice to put this in a package.

**Comment by johnsonw** [comment]
@mdiep25 are you referring to the instructions at https://whamcloud.github.io/Online-Help/docs/Install_Guide/ig_docker_stack.html? Are you thinking that we could have an rpm containing the docker-compose file? If we were to do this, where should this file be installed when installing the rpm?
