### ISSUE TITLE
Remove all usages of parking lot from iml-agent

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1479]
The iml-agent currently uses `parking-lot` in a few places. This will block the entire task when a lock is acquired.

Instead uses a futures-compatible locking mechanism.

**Comment by utopiabound** [comment]
For postman this requires `DaemonPlugin::teardown()` to become async.

**Comment by mkpankov** [comment]
Seems in some places we won't be able to do the replacement.

One of these:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/master/iml-agent/src/daemon_plugins/action_runner.rs#L71

If we switch to `futures::lock::Mutex`, it returns a future, so we have to use `.lock().await`, and `await` can only be used in `async` functions. Here it's a trait method, and it's not supported by compiler yet.

Looking at others now.

**Comment by mkpankov** [comment]
Apparently all of our usages of `Mutex` are in trait methods, so can't replace any of it with futures at the moment.

**Comment by jgrund** [comment]
> If we switch to futures::lock::Mutex, it returns a future, so we have to use .lock().await, and await can only be used in async functions. Here it's a trait method, and it's not supported by compiler yet.

`async` directly isn't supported, but any use of async can be pinned and boxed which can then be used in a trait method.

**Comment by mkpankov** [comment]
Code I was referring to:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/master/iml-agent/src/http_comms/session.rs#L190

`&mut info.lock()` becomes `&mut *(info.lock().await)` and it snowballs from there.

This is with signature converted to `-> Pin<Box<dyn Future ...`.

**Comment by mkpankov** [comment]
Made changes to all `Session`'s methods except `teardown`.

For teardown it's really complicated as we don't have a way to prevent borrowing the `Sessions`, and that borrow needs to live for `'static`.

https://github.com/whamcloud/integrated-manager-for-lustre/pull/1513/commits/d4cc088d49c456418915d6ad14d68df8efea42cb#diff-097c3716dcec898101971ec6913b99edR159

It would be possible if we had a way to strip `Arc<RwLock<...>>` in `teardown` and consume the inner value instead.
