### ISSUE TITLE
Determine the best way to add stratagem profiles to docker stack

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1541]
The RPM based approach adds stratagem profiles manually by running the following command:
```
chroma-config profile register ./stratagem-server.profile
```
However, in a docker stetup we do not have the ability to run this command. To work around this, I log into the job scheduler container and run the the following python script:
```
import sys, os
os.environ["DJANGO_SETTINGS_MODULE"] = "settings"
sys.path.insert(0, "/usr/share/chroma-manager")
from chroma_core.lib.service_config import register_profile
p = open("/tmp/stratagem-server.profile")
register_profile(p)
p2 = open("/tmp/stratagem-client.profile")
register_profile(p2)
```

We need to provide a better solution.

**Comment by jgrund** [comment]
Profiles / repos are added in `container_setup`.

https://github.com/whamcloud/integrated-manager-for-lustre/blob/baf536b02c70695c7188faaab4e9ee7d07742faa/chroma_core/lib/service_config.py#L700-L707

All we need to do is ensure that profile is in place prior to `container_setup` being run.
