### ISSUE TITLE
Investigate shrinking docker image sizes

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1555]
While working on #1549 I observed that the total size of our images is quite large.

tar archive:

![Screen Shot 2020-02-03 at 9 23 25 AM](https://user-images.githubusercontent.com/458717/73660772-dc02c900-4666-11ea-802b-92ab00127606.png)

tgz archive:

![Screen Shot 2020-02-03 at 9 24 00 AM](https://user-images.githubusercontent.com/458717/73660813-f2a92000-4666-11ea-8a75-cc62d496f97b.png)

resulting RPM:

<img width="308" alt="Screen Shot 2020-02-03 at 2 43 03 PM" src="https://user-images.githubusercontent.com/458717/73685356-074fdd00-4694-11ea-9643-765e0ceb8ece.png">

We should investigate how we can shrink the total archive size.

**Comment by jgrund** [comment]
n.b. `dive` is a useful tool for diagnosing what's in each layer. Can be installed via homebrew on macos.

**Comment by johnsonw** [comment]
I can investigate this since i'm in this space if you want.

**Comment by jgrund** [comment]
Sure. I think using common base images (try CentOS 8 with curl as a base everywhere instead of CentOS 7 / Ubuntu / alpine) can be an easy way to get some space back.

**Comment by jgrund** [comment]
I should also mention that named dockerignore files don't appear to work. I added a single .dockerignore in #1549 which you may want to look at using.

**Comment by jgrund** [comment]
Looks like after code removal lands this image will be around 500MB. That should be good enough for now.

![Screen Shot 2020-03-16 at 4 57 41 PM](https://user-images.githubusercontent.com/458717/76799182-72b6bf80-67a7-11ea-8310-fa94ab61e61f.png)
