### ISSUE TITLE
Update integration test framework to work with docker

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1557]
Currently, the integration test framework is designed to work with vagrant. Since we support both a manager node as well as a docker stack, the integration test framework should be enhanced to support a docker stack as well. This means that the test framework should be able to deploy and remove the docker stack and any other docker commands related to setting up a cluster.

**Comment by jgrund** [comment]
Some notes on this:

- Once #1549 lands, I'll add it to the https://build.whamcloud.com/view/IML/job/manager-for-lustre/ job. Then we can install that RPM  and use it in a new jenkins job.
- Do we want to run docker on the host or in a VM? If in a VM, perhaps we should create a new vagrant provisioner for installing the RPM and setting things up.

**Comment by mkpankov** [comment]
I'd very much run docker "on the host" where possible. When I'm running a development Linux in a VM I don't want another VM inside :slightly_smiling_face:

**Comment by jgrund** [comment]
> I'd very much run docker "on the host" where possible. When I'm running a development Linux in a VM I don't want another VM inside 🙂

There is an issue to consider for those of us running macos as we can't run docker stack reliably.

**Comment by johnsonw** [comment]
Yeah that's a good question.. I almost never run locally now since we have onyx available to us.
