### ISSUE TITLE
Could show specific server/filesystem/etc. in breadcrumbs

### ISSUE THREAD

**Issue by ip1981** [whamcloud/integrated-manager-for-lustre#1577]
Currently breadcrumbs looks like `/ Filesystems / Filesystem Details`, it might be better as `/ Filesystem / qwerty` with the name of the filesystem currently viewed. The same for servers and other similar entities.

**Comment by jgrund** [comment]
Given the current structure of the breadcrumbs, we aren't guaranteed that the next path will be a detail page corresponding to a parent page.

 GIven that, we should keep the differentiator ex:

`/ Filesystem / Filesystem: qwerty`
