### ISSUE TITLE
Add a well-known directory for loading IML data

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1584]
Add a well-known directory that will be mounted by docker, and can contain various pieces useful by IML.

Things to look for:

- ssh key for server auth
- server profiles to load.
- initial password.

**Comment by utopiabound** [comment]
Profiles are straight-forward, since they live in the DB.
non-default repos can live in `/var/lib/chroma/repo/` without any problem.
Initial Password is straightforward given the iml_pw secret
SSH Key is tricky, we could override shared key with "private key" and just point to the key copied in.
