### ISSUE TITLE
Improve relative time appearance 

### ISSUE THREAD

**Issue by ip1981** [whamcloud/integrated-manager-for-lustre#1663]
Following up #1633 and #1662 .

There are things to be improved:

1. Work with string representation of dates. If we can't calculate relative time for any reason, we should show the original string.
2. If we calculated relative time, we show an element with that relative time plus a tooltip showing the original time.
3. Do something when a date is in the future relatively to the server date.

**Comment by jgrund** [comment]
#2 sounds reasonable, What is the situation where we can't calculate relative time for #1? If we can't get a successful response for a session, the rest of the app is basically non-functional.

**Comment by ip1981** [comment]
> What is the situation where we can't calculate relative time for #1?

Hypothetically, server time might not be fetched yet. We also may fail to parse the date. So #1 is just a precaution.
