### ISSUE TITLE
Failed Preflight checks should print details

### ISSUE THREAD

**Issue by mdiep25** [whamcloud/integrated-manager-for-lustre#1664]
When preflight checks fail, it should print the details of failed checks.

**Comment by utopiabound** [comment]
@mdiep25,
Did you cat the key into `iml`?
```
cat id_rsa | iml server add --auth shared --hosts host-name --profile stratagem_client
```

**Comment by jgrund** [comment]
![Screen Shot 2020-03-25 at 12 29 31 PM](https://user-images.githubusercontent.com/458717/77560828-4defd580-6e94-11ea-8980-00a7ffd81875.png)
