### ISSUE TITLE
Reloading docker does not add new profiles in the /etc/iml-docker/setup directory

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1680]
**Describe the bug**
When stopping iml-docker and adding a new profile to /etc/iml-docker/setup, I noticed that the profile was not present after starting iml-docker.

**Expected**
I should be able to stop iml-docker, add a new profile to /etc/iml-docker/setup, start iml-docker, and see the new profile when attempting to add a new server.

**Comment by ip1981** [comment]
For this to work `/etc/iml-docker/setup` should be mounted at run time. I see that currently it is only available at a docker image build time.

**Comment by jgrund** [comment]
Instead of fixing this by having the iml_setup container try to do a profile add on each swarm start, I'm going to add a new command which will take input and add a new profile `cat my_profile.json > iml server profile add`

**Comment by jgrund** [comment]
I actually just tested this and it currently does work.

`iml_setup` runs when the swarm starts and is idempotent. It reads in the profiles and adds them correctly.
