### ISSUE TITLE
Ensure services always running in docker stack

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1682]
If a service exits (e.x. warp-drive having an internal error) it does not get scaled back up.

We should probably enforce replicas=1 for all relevant services in the docker-compose.yml file. 

ref: https://docs.docker.com/compose/compose-file/#replicas

**Comment by ip1981** [comment]
Replicas appears different, at least semantically. Maybe it will be [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy).

**Comment by jgrund** [comment]
> Replicas appears different, at least semantically. Maybe it will be restart policy (docker-compose). 

The production scenario uses docker stack so we can't use any items that are docker-compose only (which restart policy is).

**Comment by ip1981** [comment]
No, this is not docker-compose only, this is actually a docker's feature (available in docker-compose).

**Comment by jgrund** [comment]
whoops, you're right. 

We're actually already using restart policies, interesting that the container is not being rescheduled in this case:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/ff6b51d688dded7dc8a8edef4e29e1c65a4e5bb2/docker/docker-compose.yml#L2-L6
