### ISSUE TITLE
IML favicon should be customizable

### ISSUE THREAD

**Issue by mdiep25** [whamcloud/integrated-manager-for-lustre#1700]
I noticed the favicon is still whamcloud logo. we should able this to be customizable

**Comment by ip1981** [comment]
Maybe we can have something like a "branding" directory, which would include favicon.png, logo.svg. Will be overridable by an environment variable like IML_BRANDING_DIR. Plus IML_BRANDING_NAME for a plain text.

**Comment by jgrund** [comment]
I think that should be the end-goal for this work. 

It's worth keeping things in the binary as well that we know will always be relevant as it will avoid extra network calls.
