### ISSUE TITLE
IML CLI fs list / show does not display space, inode usage, or client count.

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1719]
When running `iml filesystem list` or `iml filesystem show fs` we get something like the following:

```
+------+-----------+-----------------+-----------------+---------+------+------+
| Name | State     | Space           | Inodes          | Clients | MDTs | OSTs |
+------+-----------+-----------------+-----------------+---------+------+------+
| fs   | available | Calculating ... | Calculating ... | 0       | 2    | 10   |
+------+-----------+-----------------+-----------------+---------+------+------+
| fs2  | available | Calculating ... | Calculating ... | 0       | 1    | 10   |
+------+-----------+-----------------+-----------------+---------+------+------+
```

This is because stats have been removed from the main db and are now only available via influx. We should query the relevant /influx endpoint to get these values and fill them in the table.

**Comment by ip1981** [comment]
Worth moving influx queries into a separate crate?

**Comment by jgrund** [comment]
Maybe. What do you have in mind?

**Comment by ip1981** [comment]
At least we could avoid duplicating queries and responses. But maybe we can have a single async function usable the the both native and wasm targets.

**Comment by jgrund** [comment]
Yeah, I see the value of abstracting queries used in multiple places, just wondering if we could spitball what the API would look like.
