### ISSUE TITLE
Logs icon should not be visible for anonymous users

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1728]
When a user is anonymous, they should not see the logs icon in the sidebar

<img width="147" alt="Screen Shot 2020-03-25 at 7 33 23 PM" src="https://user-images.githubusercontent.com/458717/77595528-c3c56280-6ecf-11ea-98d2-57cf3250c4b4.png">

**Comment by ip1981** [comment]
What about the other icons? They seem inactive for the anonymous user.
