### ISSUE TITLE
Agent should read private.pem and self.cert instead of creating identy.pfx

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1731]
Instead of calling out to create a tertiary file, private.pem and self.cert should be read into a single buffer and passed to `Identity::from_pem()` instead of using `from_pkcs12_der()`

https://github.com/whamcloud/integrated-manager-for-lustre/blob/675374cd47f709d1a3d59381fa6459d4329362f2/iml-agent/src/http_comms/crypto_client.rs#L16-L18

Related to Pull #1730

**Comment by mkpankov** [comment]
Switching to `from_pem` requires switching to `rustls` backend:
```rust
    Client::builder()
        .use_rustls_tls()
```

This causes nginx to stop accepting connections for whatever reason:
```
2020/07/03 08:07:10 [crit] 19877#0: *22066 SSL_do_handshake() failed (SSL: error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long error:0D068066:asn1 encoding routines:ASN1_CHECK_TLEN:bad object header error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:Type=X509 error:1408900D:SSL routines:ssl3_get_client_certificate:ASN1 lib) while SSL handshaking, client: 10.73.10.11, server: 0.0.0.0:443
```

Working on it.
