### ISSUE TITLE
GUI: Breadcrumb user should reflect first + last name if present

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1734]
When the first and last name are entered in the user field, The logged in user will update in the top right.

The current user on the breadcrumb trail should also update.

![Screen Shot 2020-03-26 at 10 45 36 AM](https://user-images.githubusercontent.com/458717/77662145-e0a27a00-6f51-11ea-8638-6ad7441cda62.png)

**Comment by ip1981** [comment]
Updating breadcrumbs might be nontrivial to implement because we only store strings. Plus first+last name can be too long for breadcrumbs. User id (username) seems the most appropriate for being immutable, no?

**Comment by ip1981** [comment]
I think it makes sense to update the current breadcrumb with the current page's title, iff the latter changes (and make it change with the user's names?)

**Comment by ip1981** [comment]
By the way, we should compare breadcrumbs by URL only (that's easy), automatically we will be able to update them without any special code.
