### ISSUE TITLE
Allow NTP to use the `stratagem_existing_client`

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1743]
Currently, stratagem verifies that the stratagem_client profile is installed on the client. We also have the `stratagem_existing_client` profile, which is also valid. This code should be updated to allow for either client to be installed. See https://github.com/whamcloud/integrated-manager-for-lustre/blob/master/chroma_api/stratagem.py#L158

**Comment by johnsonw** [comment]
Also job_scheduler.py L#1913

**Comment by jgrund** [comment]
![Screen Shot 2020-03-27 at 12 14 43 PM](https://user-images.githubusercontent.com/458717/77776724-d604e500-7024-11ea-840e-294d98a0a2f0.png)
