### ISSUE TITLE
Stratagem config tooltip z-index higher than sidebar

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1748]
![Screen Shot 2020-03-27 at 12 45 46 PM](https://user-images.githubusercontent.com/458717/78033239-1ff70f00-7334-11ea-821c-4c4fc321cca9.png)

**Comment by ip1981** [comment]
This should fix the problem :)

![Doc - 15-4-20 - 13-53 - p1](https://user-images.githubusercontent.com/131844/79334581-d6f0ae80-7f20-11ea-9a22-4a060acca67f.jpg)
