### ISSUE TITLE
Add and utilize snapshots in integration tests

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1750]
Currently, the integration tests setup a fully functioning filesystem and add it to IML. This includes both ldiskfs and zfs filesystems. When performing tests on these filesystems we should taking into account the fact that snapshots are being taken along the way. While we can't take snapshots of docker, we can still restore snapshots of the server nodes and re-add them to a clean docker setup to allow for faster testing. 

To use snapshots effectively, a tree structure of snapshots should be generated at the beginning of a test. The test can then ask the snapshot manager for a particular snapshot. If the snapshot exists, it will restore the snapshot on each of the server nodes. If the snapshot does not exist, it will go to the nodes ancestor and check if that snapshot exists. If so, it will return that snapshot to the test. The test will need to know how to respond to which snapshot is available. For example, consider a test for an ldiskfs filesystem. If a snapshot exists where the filesystem has been configured on the storage servers, then we can easily start from that point in time and focus on running the test. If this snapshot does not exists, we will look at the next possible snapshot (ancestor in the tree), which might be when the server was deployed and all necessary software was installed. If it finds this snapshot, it can restore at this point, but it will still be responsible for creating a filesystem. 

We may need to specify a list of commands to run depending on what snapshot is being restored. For example:

"server_deployed" => [configure_ntp, create_ldiskfs_fs, detect_fs],
"bare" => [configure_docker_network, server_add(servers), ...]

As i'm thinking about this more, this feels more complicated than it should be. I'd like to simplify this a bit. Any thoughts?

**Comment by jgrund** [comment]
I'd take a look at a crate like https://docs.rs/petgraph/0.5.0/petgraph/ .

If you build the tree beforehand and then have slots to track whether each spot was provisioned, it should be fairly simple to find the starting point and go from there.

**Comment by johnsonw** [comment]
Sample DAG I will be modeling:

![graph](https://user-images.githubusercontent.com/1100657/79255925-28336c00-7e55-11ea-8404-d1f2cce23f49.jpg)

**Comment by johnsonw** [comment]
I now have the graph integrated along with unit tests. The graph api allows for easy generation of dot files. I passed in a full set of snapshots and generated the graph. Here is the dot output:

![snapshots dot](https://user-images.githubusercontent.com/1100657/79627561-6d7ec480-8107-11ea-9a1a-2ddc7a190dbf.jpg)
