### ISSUE TITLE
Store device tree serialized to JSON in Postgres

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1761]
This would allow to avoid manual serialization / deserialization to JSON and relational tables.

Points to investigate:
- [x] Would it support `warp-drive` pattern of LISTEN / NOTIFY
- [x] Would it allow to remove complicated code from `iml-devices`
- [x] Would it be generally convenient to use

The matter of PostgreSQL version is also important. Currently our RPM specifies `>= 9.2` and 9.2 has pretty basic support of JSON. Consider:
- 9.2:
  - [Data type](https://www.postgresql.org/docs/9.2/datatype-json.html)
  - [Functions](https://www.postgresql.org/docs/9.2/functions-json.html)
- 12 (current):
  - [Data type](https://www.postgresql.org/docs/12/datatype-json.html)
  - [Functions](https://www.postgresql.org/docs/12/functions-json.html)

So that raises the question of whether we can up the required version of PostgreSQL.

**Comment by mkpankov** [comment]
Listening to JSON notifications seems to be possible:
https://coussej.github.io/2015/09/15/Listening-to-generic-JSON-notifications-from-PostgreSQL-in-Go/

**Comment by jgrund** [comment]
> So that raises the question of whether we can up the required version of PostgreSQL.

We should be able to do this, if there is something in later versions that would be useful / required.

**Comment by mkpankov** [comment]
> - [x] Would it support `warp-drive` pattern of LISTEN / NOTIFY

Yes, it seems so
https://coussej.github.io/2015/09/15/Listening-to-generic-JSON-notifications-from-PostgreSQL-in-Go/

> - [x] Would it allow to remove complicated code from `iml-devices`

No, the most complicated code such as 
https://github.com/whamcloud/integrated-manager-for-lustre/blob/warpdrive-dev-2/iml-services/iml-devices/src/build_new_state.rs#L18
and
https://github.com/whamcloud/integrated-manager-for-lustre/blob/warpdrive-dev-2/iml-services/iml-devices/src/virtual_device.rs#L98
will stay.

It will allow us to remove
https://github.com/whamcloud/integrated-manager-for-lustre/blob/warpdrive-dev-2/iml-wire-types/src/db.rs#L957

> - [x] Would it be generally convenient to use

In the code that computes changes it will stay the same. Only serde will change, and that part is not difficult or problematic.

**Comment by jgrund** [comment]
So, the complicated code in using the relational model is not only from turning a DAG into a relational model, but also from the fact that the explored relational approach flattened device trees into a singular list. This was done on the agent-side and basically was very lossy, as you need to reassemble the flat list to a DAG not only on the incoming host, but also every other host.

This is really where the complexity lives.

In contrast, if we ship the device-scanner DAG as is, we just need to lift out shared storage between hosts to build the cluster-wide view. This is already being done in the device-plugin today. In addition, all the reassembling of a flat list of devices / device-hosts can disappear as we would just need to resolve shared-storage on each tick.

**Comment by mkpankov** [comment]
Are you saying that ideally you'd get rid of state flattening in device-scanner too?
https://github.com/whamcloud/device-scanner/blob/master/device-scanner-daemon/src/state.rs#L299

**Comment by jgrund** [comment]
Well, state flattening was added as part of the patches to store data relationally.

By default (in current master) the state emitted from `device-scanner` is a DAG.

ref: https://github.com/whamcloud/integrated-manager-for-lustre/blob/a022c87864e3f7407274c9860f5b644311e0835b/iml-services/iml-device/fixtures/devtree.json

**Comment by mkpankov** [comment]
I got the basic version of storing devices working

![Peek 2020-04-16 12-25](https://user-images.githubusercontent.com/393741/79439451-868b5680-7fdd-11ea-95d5-01ffe8990ecc.gif)

**Comment by jgrund** [comment]
This is done.
