### ISSUE TITLE
Create django model for HotPools

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1772]
**Assumptions:**
* Only one HP setup for a given hot pool
* Services will be run by systemd

**Requirements:**
* Needs to account for HPv3 (will have a cache warmer in addition to lpurge and lamigo).
* IML mailboxes may or may not be used.
* Account for services being pacemaker HA services or plain systemd in non-HA environment
* Model is mirrored in iml-orm

**Comment by jgrund** [comment]
Is this only for the monitoring side, or also management?

**Comment by utopiabound** [comment]
Management of ha-enabled or even systemd enabled hotpools shouldn't be an issue.
