### ISSUE TITLE
Logged out users can still see logged-in resources

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1805]
if you log out, you still have access to what only logged in users have access, e.g. you can follow links on the views to other views that are unavailable to logged out users, or you can use breadcrumbs for navigation to such views.

We should use the session change monitoring to change breadcrumb display and redirect from authorized pages.

**Comment by ip1981** [comment]
Maybe we should reset the state and redirect to the main page. Just like if a user reload the tab or restart the browser.
