### ISSUE TITLE
OSTs cannot be added to ostpools

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1853]
Consider the following:

```
iml filesystem pool create fs fast
iml filesystem pool grow fs fast fs-OST0000
```

I would expect the `chroma_core_ostpool_osts` to contain the ost I just added however:

```
chroma=> select * from chroma_core_ostpool;
 id | name | not_deleted | content_type_id | filesystem_id
----+------+-------------+-----------------+---------------
  1 | fast | t           |              38 |             1
  3 | slow | t           |              38 |             1
(2 rows)

chroma=> select * from chroma_core_ostpool_osts;
 id | ostpool_id | managedost_id
----+------------+---------------
(0 rows)
```

Updating (growing) the ostpool was reported as successful:

![Screen Shot 2020-05-01 at 11 23 46 AM](https://user-images.githubusercontent.com/458717/80816850-45c73c00-8b9e-11ea-99d1-1979138122fd.png)

**Comment by utopiabound** [comment]
OST additions to pools flow up from ostpool daemon on servers.

**Comment by jgrund** [comment]
FWIW, this was many minutes after the initial command.
