### ISSUE TITLE
Command modal should provide to cancel jobs

### ISSUE THREAD

**Issue by nlinker** [whamcloud/integrated-manager-for-lustre#1876]
Sometimes the job execution takes too much time, we need to be able to cancel them from the UI:

![Servers](https://user-images.githubusercontent.com/940363/81307222-4120ed00-90a2-11ea-83b6-9d4d740cb6cf.png)

It may be a button or a ban icon with an acknowledgement to avoid accidental clicks.

**Comment by jgrund** [comment]
Previously this was a dropown (as theoretically there could be other things to do besides cancel)

**Comment by jgrund** [comment]
For now a cancel button works though.

**Comment by nlinker** [comment]
Cancel code from the old gui:
https://github.com/whamcloud/GUI/blob/0cbf30d7ab36746619a3b53617c1a14a8e8d8622/source/iml/command/command-modal.js#L101-L125

**Comment by jgrund** [comment]
available transitions (of which cancel is usually one) are read off the job itself:

https://docs.rs/iml-wire-types/0.2.1/iml_wire_types/struct.Job.html#structfield.available_transitions
