### ISSUE TITLE
Destroying iscsi vm sometimes hangs

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1890]
We use vagrant to manage all cluster vm's, which takes care of cleaning up all attached storage controllers and virtual hard disks. Most of the time this works well, but occasionally we have seen the iscsi node get stuck on the `destroy` command. I spent some time looking into why this happens and it seems that the iscsi vm is holding onto some kind of resource, though I haven't been able to determine what that resource is yet. Here is some useful log output:

```
AIOMgr: Flush failed with VERR_INVALID_PARAMETER, disabling async flushes
...
00:15:09.141920 Console: Machine state changed to 'Stopping'
00:15:09.142240 Console::powerDown(): A request to power off the VM has been issued (mMachineState=Stopping, InUninit=0)
00:15:09.142526 Changing the VM state from 'RUNNING' to 'POWERING_OFF'
...
```

There are three virtual cpu’s on the iscsi vm, each of which seem to complete their shutdown process without any issue. After all three virtual cpu’s are shut down, we then get the following message:

```
00:15:09.146297 PDMR3PowerOff: after     3 ms, 1 loops: 1 async tasks - ahci/0
63:55:21.294952 ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={The virtual machine is being powered down}, preserve=false aResultDetail=0
```

Running an strace also shows that the VBoxSVC service is continually running the following system commands:

```
futex(0x10fc2e8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x10fe51c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x10fe518, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
sched_yield()                           = 0
read(4, "\372", 1)                      = 1
select(5, [4], NULL, [4], NULL)
```

Looking at information regarding the vm will show that there are still many attached storage controllers and virtual hdds. I have posted both on the vagrant repo and the virtualbox forums about this issue:

Vagrant: https://github.com/hashicorp/vagrant/issues/11608
Virtualbox: https://forums.virtualbox.org/viewtopic.php?f=7&t=98130

To help get more information, i've updated #1872 such that it vagrant runs all commands with debug logging. This will hopefully show more pertinent information about the issue so we can understand it better.

**Comment by jgrund** [comment]
destroy has been updated to do a suspend first.
