### ISSUE TITLE
Command modal should open with first command expanded

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1897]
When opening a command modal, the first command should be expanded by default. This will save the user having to click to open and is useful when the modal is opened in response to a command in progress.

## Current behavior 

<img width="799" alt="Screen Shot 2020-05-14 at 7 45 27 AM" src="https://user-images.githubusercontent.com/458717/81930832-1ad5e280-95b7-11ea-9f82-ddd426abfb45.png">

## Desired behavior

<img width="807" alt="Screen Shot 2020-05-14 at 7 47 54 AM" src="https://user-images.githubusercontent.com/458717/81930951-4b1d8100-95b7-11ea-9473-46a3f0ec7898.png">

**Comment by nlinker** [comment]
![out](https://user-images.githubusercontent.com/940363/89533920-fd12c500-d815-11ea-886a-8594d6a4295f.gif)
