### ISSUE TITLE
When Session data is over 1MB, the service can't receive it

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#1939]
Reproduction: check out the `tree` branch in this repo.

There's a test service and daemon plugin:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/tree/iml-services/iml-size-test/src/main.rs
https://github.com/whamcloud/integrated-manager-for-lustre/blob/tree/iml-agent/src/daemon_plugins/size_test.rs

On `oss1`:
```
[root@oss1 vagrant]# journalctl -fu rust-iml-agent
-- Logs begin at Thu 2020-06-04 07:03:06 UTC. --
Jun 04 10:15:57 oss1.local iml-agent-daemon[23866]: Jun 04 10:15:57.165  INFO iml_agent::daemon_plugins::size_test: Sending 1245185 bytes (create_session)
Jun 04 10:15:58 oss1.local iml-agent-daemon[23866]: Jun 04 10:15:58.329  INFO iml_agent::daemon_plugins::size_test: Sending 1245185 bytes (create_session)
Jun 04 10:15:59 oss1.local iml-agent-daemon[23866]: Jun 04 10:15:59.188  INFO iml_agent::daemon_plugins::size_test: Sending 1245185 bytes (create_session)
...
```

On `adm`:
```
[root@adm vagrant]# journalctl -fu iml-size-test
-- Logs begin at Thu 2020-06-04 07:00:00 UTC. --
Jun 04 09:31:54 adm.local iml-size-test[30470]: Jun 04 09:31:54.843  INFO iml_size_test: Received 8192 datums from mds2.local
Jun 04 09:31:54 adm.local iml-size-test[30470]: Jun 04 09:31:54.951  INFO iml_size_test: Received 8192 datums from oss2.local
Jun 04 09:32:04 adm.local iml-size-test[30470]: Jun 04 09:32:04.533  INFO iml_size_test: Received 8192 datums from oss1.local
Jun 04 09:32:05 adm.local iml-size-test[30470]: Jun 04 09:32:05.935  INFO iml_size_test: Received 8192 datums from oss2.local
Jun 04 09:32:16 adm.local iml-size-test[30470]: Jun 04 09:32:16.928  INFO iml_size_test: Received 8192 datums from oss2.local
Jun 04 10:16:48 adm.local systemd[1]: Stopping IML Size Test Service...
Jun 04 10:16:48 adm.local systemd[1]: Stopped IML Size Test Service.
Jun 04 10:16:52 adm.local iml-size-test[31975]: Jun 04 10:16:52.573  INFO iml_size_test: Server starting
Jun 04 10:16:52 adm.local systemd[1]: Started IML Size Test Service.
Jun 04 10:16:52 adm.local iml-size-test[31975]: Jun 04 10:16:52.675  INFO iml_rabbit: purged queue rust_agent_size_test_rx
```

As one can see, with a `Vec` of 8192 elements it works, with 16384 - it doesn't. The numbers are changed here:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/tree/iml-agent/src/daemon_plugins/size_test.rs#L33

Size estimation is just that - estimation, because we're sending `Value` not `String`. But it seems to be a pretty accurate estimation.

To rule out some of possible culprits, RabbitMQ [claims](https://github.com/rabbitmq/rabbitmq-server/issues/147#issuecomment-470882099) to support messages up to 512 MB, so we need to look at other components in delivery chain.

@ip1981 has pinpointed the possible point to be in Nginx configuration here:
https://github.com/whamcloud/integrated-manager-for-lustre/blob/tree/chroma-manager.conf.template#L287

Didn't check its effect yet.

**Comment by mkpankov** [comment]
Simply increasing `client_body_buffer_size` to `8m` didn't help.

**Comment by ip1981** [comment]
I didn't mean that was the exact place to look at :) You have to figure out which location entry is involved. And client buffer size doesn't matter, max body size does (which is 1M by default).

**Comment by jgrund** [comment]
`/agent2/message` receives Rust agent messages here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/6856f8aeef0b9c96eacf31d2273d34d61af44225/chroma-manager.conf.template#L304-L317

The nginx error log should have entries if items are being dropped.

What are we sending that is > 1MB in size?

**Comment by mkpankov** [comment]
Ok so it can be fixed with max body size increase, and errors do show up in `error.log`.

That got me thinking though - if this is happening with just 10 pools, won't it be an issue in production? I.e. with 100 pools a single device tree will end up being roughly the same size.

@jgrund what do you think?

**Comment by jgrund** [comment]
It would make sense to update the endpoint to match:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/6856f8aeef0b9c96eacf31d2273d34d61af44225/chroma-manager.conf.template#L287-L288

In addition, we should look at send compression on the agent side (I think this just landed in recent reqwest).
