### ISSUE TITLE
Make chart icons blue in tree view

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1983]
The chart icons in the tree-view should be blue to indicate that they can be clicked. They should also have a tooltip when they are hovered over.

**Comment by johnsonw** [comment]
![image](https://user-images.githubusercontent.com/1100657/85033690-3badcc80-b14f-11ea-8c0b-6fad4a3d3875.png)

![image](https://user-images.githubusercontent.com/1100657/85033721-4700f800-b14f-11ea-935f-9b50ed93ccd7.png)

![image](https://user-images.githubusercontent.com/1100657/85033777-54b67d80-b14f-11ea-9cde-33b9667c24dd.png)

**Comment by jgrund** [comment]
Can we change the tooltip to say something generic like "view statistics"?
