### ISSUE TITLE
LVM Metadata setup doesn't work because of unsuccessful lvcreate

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#2027]
```   
vagrant provision --provision-with=install-ldiskfs-no-iml,configure-lustre-network,create-ldiskfs-lvm-fs,ha-ldiskfs-lvm-fs-prep
VBOX_PASSWD=<ROOT_PW_HERE>
vagrant provision --provision-with=ha-ldiskfs-lvm-fs-setup
```

This seems to fail in `create-ldiskfs-lvm-fs` around

```
lvcreate -n mgt -l 100%FREE --addtag pacemaker mgt_vg
```

supposedly because `/etc/lvm/lvm.conf` has empty `volume_list` in it. For `lvcreate` to work, it has to have correct volume groups in it or the property should be missing from `lvm.conf` altogether.

**Comment by utopiabound** [comment]
It should only have empty `volume_list` AFTER it runs lvcreate.  Is this not the first time you've run it?

**Comment by jgrund** [comment]
The issue I've hit is `lvcreate` fails during provision on the MGS for some reason. I think the volume_list bit is referencing the fact that it needs to be removed prior to running lvcreate again by hand, but that's orthogonal to the root issue.
