### ISSUE TITLE
iml server remove vs force-remove

### ISSUE THREAD

**Issue by beevans** [whamcloud/integrated-manager-for-lustre#2033]
"iml server remove" requires --delete_hosts where "iml server force-remove" just uses the server to delete.  I'd prefer the "force-remove" style.

**Comment by jgrund** [comment]
@beevans PRs welcome.

This should be a simple fix

https://github.com/whamcloud/integrated-manager-for-lustre/blob/a714020054a429f88726783f24a7d8248316997c/iml-manager-cli/src/server.rs#L81-L86

The `Remove` variant just needs to be updated to look like the `ForceRemove` variant.
