### ISSUE TITLE
IML server add command incorrect in test

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#2052]
In latest docker tests I am seeing:

```
16:19:49  USAGE:
16:19:49      iml server add [FLAGS] [OPTIONS] <hosts>... --profile <profile>
16:19:49  
16:19:49  FLAGS:
16:19:49          --force      Always continue if command fails
16:19:49      -h, --help       Prints help information
16:19:49          --prompt     Prompt to continue if command fails
16:19:49      -V, --version    Prints version information
16:19:49  
16:19:49  OPTIONS:
16:19:49      -a, --auth <auth>            Authentication Type (shared, password, private) for "private" key is read from stdin
16:19:49                                   [default: shared]
16:19:49      -P, --password <password>    Password for "password" or password for "private" key
16:19:49      -p, --profile <profile>      The profile to deploy to each host
```

This is due to the following code which needs to be updated for the new host format:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/7f1756955f4c020d4a44be4ec04659209a41684b/iml-system-test-utils/src/iml.rs#L29-L43

In addition, these tests are passing despite the fact that no servers have been added.

This means that both the server add and filesystem detect commands are passing, despite the fact that nothing was added.

**Comment by ip1981** [comment]
This is mine.

**Comment by jgrund** [comment]
@ip1981 You'll need to investigate why tests are continuing past this step. when a command is called improperly it should return `1` which in turn should be stopping the tests with an error.

**Comment by jgrund** [comment]
I see why it's passing. It's because the `-h` flag was overloaded but now it's printing help (which returns 0).
