### ISSUE TITLE
Persist Lustre mounts on monitored installs

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#2057]
When setting up a monitored install using the vagrant provisioning scripts:
```
configure-lustre-network,create-ldiskfs-fs,create-ldiskfs-fs2,mount-ldiskfs-fs,mount-ldiskfs-fs2
```
The mounts will live until the nodes are rebooted. Once the nodes are rebooted the targets will no longer be mounted, which results in the following:

![image](https://user-images.githubusercontent.com/1100657/87057616-156ed000-c1d5-11ea-96e6-1a0cb3f7cca0.png)

To ensure that the mounts persist between reboots a new script needs to be added for both monitored ldiskfs and zfs such that the mounts are managed by HA. The integration tests should use this new provisioning script to ensure the mounts persist between reboots.

**Comment by jgrund** [comment]
To be clear, we should pursue https://github.com/whamcloud/integrated-manager-for-lustre/issues/1777 instead of this one. 

That means, we should not have a provision that does automated testing without HA.
