### ISSUE TITLE
HA Clusters

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#2139]
Instead of `managedtarget.ha_cluster_peers` it would be better to have a list HA clusters with member hosts.

The use case for this is to find 1 host from each cluster for a given filesystem to run resource creates on.

Given the current setup: finding HA Groups for a filesystem could be accomplished by mapping all ManagedTargetMounts (grouped by target_id) to groups of MangedHosts and then finding unique sets.

**Comment by utopiabound** [comment]
If there's an easier / cheaper way to do this without creating DB tables, that's fine too.

Maybe something like:
```SQL
SELECT a.host_id, b.host_id from chroma_core_managedtargetmount as a, chroma_core_managedtargetmount as b where a.target_id = b.target_id AND a.host_id < b.host_id GROUP BY a.host_id, b.host_id;
```
Plus a WHERE to ensure a target_id is for a target in a given filesystem.

**Comment by jgrund** [comment]
Listing distinct node clusters:

```
chroma=> select array_agg(distinct corosync_node_id) from corosync_node_managed_host group by cluster_id;
              array_agg
-------------------------------------
 {"(1,mds1.local)","(2,mds2.local)"}
 {"(1,oss1.local)","(2,oss2.local)"}
```

**Comment by jgrund** [comment]
Listing distinct node clusters given a particular filesystem:

```
chroma=> SELECT array_agg(distinct rh.host_id) as cluster_nodes from targets t
chroma-> INNER JOIN corosync_target_resource r
chroma-> ON r.mount_point = t.mount_path
chroma-> INNER JOIN corosync_target_resource_managed_host rh
chroma-> ON rh.corosync_resource_id = r.id AND rh.cluster_id = r.cluster_id
chroma-> LEFT OUTER JOIN corosync_resource_bans b
chroma-> ON b.cluster_id = r.cluster_id AND b.resource = r.id
chroma-> WHERE 'fs' = ANY(t.filesystems)
chroma-> GROUP BY rh.cluster_id;
 cluster_nodes
---------------
 {1,2}
 {3,4}
(2 rows)
```

**Comment by jgrund** [comment]
graphql query:

![Screen Shot 2020-09-02 at 10 54 26 AM](https://user-images.githubusercontent.com/458717/91999944-f5f2b000-ed0a-11ea-9151-2f4c6c187518.png)
