### ISSUE TITLE
iml-task-runner: limit parallelism to number of connections in pool

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#2157]
In iml-task-runner, we do some work each tick (5 seconds) and ship it off to a separate task. Within that task, we find some fid actions and run them concurrently. Each block of fid actions is run within a transaction, so we can rollback if there is a failure of any kind. 

The amount of parallel fid actions in flight is bounded by both the number of usable workers and the db pool used for connections.

If workers are < the pool size, then when all workers are in flight there are still open connections in the pool and things work well.

If workers are >= the pool size, then we will attempt to schedule work on each tick. Each block of work will attempt to get a transaction, which will block until a connection is available. 

The connection timeout is currently set to 30 seconds; once a transaction blocks, it has this long for a previous transaction to be released or an error will be raised.

To complicate matters further, Postgres has a bounded number of total connections. Once they are all in use, all processes connected to the database will start erroring. This value is set to 100 in a default install:

```
chroma=> SHOW max_connections;
 max_connections
-----------------
 100
(1 row)
```

Given actions can be run for an undefined amount of time; we need to hold a connection open for the entire lifetime of an action, and we have a limited number of connections, we should bound parallelism of transactions to the amount of connections available in the pool.

By doing this we avoid buffering work that has 30 seconds to get a connection or suffer an error.

It should be noted that the transactional approach (which seems to be the correct one) trades performance for reliability; If we were to remove the transaction requirement I think we could keep the current approach.

**Comment by jgrund** [comment]
Thinking out loud, perhaps instead of a transaction per action we could use a combination of transactions + savepoints to scale over many actions

**Comment by utopiabound** [comment]
It does look like we need to limit the number of active workers to the pool size.  Though I wonder if we can size the pool up if there are a lot of available workers.
