### ISSUE TITLE
too many things in logs

### ISSUE THREAD

**Issue by beevans** [whamcloud/integrated-manager-for-lustre#2173]
Too many messages on by default.

in about 10 minutes:
ntp: 12252 lines
iml-agent-comms: 35135 lines
python: 3700 lines
iml-task-runner: 5683 lines
iml-journal: 33689 lines

Version: origin/master
All messages are default, no debugging has been turned on

This rapidly fills up the drive, since it's being logged to the pgsql DB, /var/log/messages, and the journalctl temp files.

**Comment by jgrund** [comment]
ref #2129

**Comment by jgrund** [comment]
ref #2231

**Comment by jgrund** [comment]
I think #2231 is the only remaining part of this to be fixed, so closing this one.
