### ISSUE TITLE
map multipath bindings to devices on vagrant

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#2197]
Iscsi creates many devices to be used on the MDS and OSS nodes. These devices are typically 5GB for MDT's and OST's. MGT's however, do not require nearly this much space. The concern is that the provisioners format and mount devices and depend on these devices being mapped to the correct mpath. For example, consider that we want to format and mount the first 5 OST devices, each being 5GB. We would expect:

/dev/mapper/mpatha => /mnt/ost1,
/dev/mapper/mpathb => /mnt/ost2,
/dev/mapper/mpathc => /mnt/ost3,
/dev/mapper/mpathd => /mnt/ost4,
/dev/mapper/mpathe => /mnt/ost5

But, what if we added a new mgt to the OSS node pair and we expected it to be mapped to the very last mpath entry (/dev/mapper/mpathu). If there is nothing to guarantee that the devices are mapped as above, then this new MGT, which is only 512MB could end up being mapped to /dev/mapper/mpathn, which should have been assigned to OST14. This creates issues where we think we are formatting and mounting ostx but we are really working on osty. To prevent this issue, we can simply ensure the bindings file maps each of the WWID's accordingly, stop the multipath service, flush it, and then start the multipath service. This will ensure that the devices are mapped as above and the new MGT, in this case, will be assigned to /dev/mapper/mpathu instead of /dev/mapper/mpathn.

**Comment by jgrund** [comment]
Hrrm, how come our current MGS consistently picks the correct volume?

**Comment by johnsonw** [comment]
The reason the mpath's are not mapped correctly is because they are mapped using alphabetic sorting instead of natural sorting. Since the MDS nodes only contain four devices, the sorting works out to be ok.

MDS Nodes:
```
mpatha (36001405f56f195148f74d2e90aec967f) dm-0 LIO-ORG ,mgt1
mpathb (36001405e845cb24abdc44a3bf562f166) dm-1 LIO-ORG ,mdt1
mpathc (3600140557febf98d4dd4f29aab36bac8) dm-2 LIO-ORG ,mdt2
mpathd (360014053cc7278c585b45418aa5bd958) dm-3 LIO-ORG ,mdt3
```

In contrast, the OSS nodes contain > 10 OST devices and thus the mapping issue presents itself:
OSS Nodes:
```
mpatha (36001405983ebaaa32a54ea7bc7de9077) dm-0 LIO-ORG ,ost1
mpathb (36001405fb8466081a7a432c8a7c84d6c) dm-1 LIO-ORG ,ost2
mpathc (3600140586f8d53ac79441c1a718b96ca) dm-2 LIO-ORG ,ost11
mpathd (36001405abf5af99e7e2494f86ede8042) dm-3 LIO-ORG ,ost12
mpathe (36001405029e65de05f546189bf0e5628) dm-4 LIO-ORG ,ost13
mpathf (360014057f6e2b8986a1401fa6909ae8d) dm-5 LIO-ORG ,ost14
mpathg (360014054733a6fcf25a408380ac9cf3d) dm-6 LIO-ORG ,ost15
mpathh (360014057a9d598d9a8d4cc5b3fd9c2bf) dm-7 LIO-ORG ,ost16
mpathi (36001405253e7bdfecd0492fbd7b92d29) dm-8 LIO-ORG ,ost17
mpathj (36001405d623c36e3ac8459ba496ce750) dm-9 LIO-ORG ,ost18
mpathk (36001405900787f8159f4086a7235bedf) dm-10 LIO-ORG ,ost19
mpathl (36001405e10d2ab02e9f4855a6b4a5795) dm-11 LIO-ORG ,ost20
mpathm (3600140544cdc92d7b9147ae8e4b1f8bd) dm-12 LIO-ORG ,ost3
mpathn (36001405d60eed889c3945f8bdf8b8a02) dm-13 LIO-ORG ,ost4
mpatho (360014051ad53300e3af4b25850d38a8a) dm-14 LIO-ORG ,ost5
mpathp (36001405cdd7af90c0134252bd5136acd) dm-15 LIO-ORG ,ost6
mpathq (360014052c749e87eee245ba8f3c9159c) dm-16 LIO-ORG ,ost7
mpathr (360014059032f2930c954c81afeb298f6) dm-17 LIO-ORG ,ost8
mpaths (36001405c1849c058f2148a390f18bf9e) dm-18 LIO-ORG ,ost9
mpatht (36001405550e93b8183d4b05942ef637e) dm-19 LIO-ORG ,ost10
```

Since the OST's are all the same size, we haven't really run into any issues. But, for example, if we were to do something with OST 4, it would modify mpathn, not mpathd as expected. Where this becomes a problem is when we want to add an MGT of 512MB to the OSS nodes. We may think we are selecting an OST but mistakenly map to the MGT, which could cause problems.

**Comment by jgrund** [comment]
Where is it that we are referring to mpath names instead of the symlinks? looked through this briefly and it seems pretty hardcoded.
