### ISSUE TITLE
zed-enhancer:  send hup signal to zfs-zed

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#2201]
`device-scanner` installs a number of zedlets to get near-realime changes from `zed`. However, these zedlets won't be picked up by default by `zed` until a restart. 

We should make sure to send a `HUP` to `zed` before starting `zed-enhancer` so that the zedlets are picked up and processed as expected.

**Comment by ip1981** [comment]
What if send an optional signal on package install?
Or send a signal before `device-scanner` starts?

**Comment by jgrund** [comment]
Either one of those should work.
