### ISSUE TITLE
Do not warn if snapshot listing cannot be found

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#2220]
On system where snapshots are not configured.

```
Sep 05 15:18:44 ai400-0a9c-vm00 iml-agent-daemon[6355]: Sep 05 15:18:44.878  WARN iml_agent::daemon_plugins::snapshot: listing failed: [("fs0a9c", CmdError(Output(Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Can\'t open the snapshot config file /etc/lsnapshot/fs0a9c.conf: No such file or directory\n" })))]
```

**Comment by ip1981** [comment]
How can we know they are not configured?

**Comment by jgrund** [comment]
In addition, the `lctl get_param mgs/MGS/live/*`  will only work where the MGT is mounted:

`Sep 06 13:43:54 mds2.local iml-agent-daemon[18529]: Sep 06 13:43:54.858  WARN iml_agent::daemon_plugins::snapshot: listing filesystems failed: exit code: 2, stdout: , stderr: error: list_param: param_path 'mgs/MGS/live/*': No such file or directory`

**Comment by jgrund** [comment]
> How can we know they are not configured?

I don't know of a reliable way to do so. I think we should move the logging to debug though. Currently it looks like there is an issue when there isn't one.
