### ISSUE TITLE
Start(ed|ing) IML Swap Emitter...

### ISSUE THREAD

**Issue by beevans** [whamcloud/integrated-manager-for-lustre#2232]
Seeing tons of Started/Starting IML Swap Emitter messages in the GUI logs.

Maybe only start it once?  Maybe not tell me when it succeeds, only fails?

Maybe filter the GUI logs for Warning/Error messages by default?

**Comment by jgrund** [comment]
> Maybe only start it once? Maybe not tell me when it succeeds, only fails?

It needs to be run on a systemd timer as there is no push based way to notify of swap changes.

There is also no way to silence the systemd timer (ref: https://github.com/systemd/systemd/issues/9328)

That leaves us with filtering this particular message before it's ingested into the db.

**Comment by costello-ian** [comment]
Hi @jgrund,

Do you have a patch, script or code to apply to a site that is also seeing this issue?

Thanks,
Ian Costello | DDN | Advanced Support Engineer

**Comment by costello-ian** [comment]
Hi @jgrund ,

I took a look at the other case you refer to and will try the Unit.SilentOnSuccess config option.

Thanks,
Ian Costello | DDN | Advanced Support Engineer

**Comment by jgrund** [comment]
Hi @costello-ian, 

As I understand it `Unit.SilentOnSuccess` was not accepted into systemd. I think the only way to silence this on the journal  side is to stop using a timer and instead use a daemon that runs on an internal timer.

I'll take a look at doing this.

**Comment by costello-ian** [comment]
Hi @jgrund,

Much appreciated!

Thanks,
Ian Costello | DDN | Advanced Support Engineer
