### ISSUE TITLE
Snapshots should not disappear from the DB

### ISSUE THREAD

**Issue by ip1981** [whamcloud/integrated-manager-for-lustre#2248]
Snapshots should not disappear from the DB due to errors.

For example, when listing cannot be performed due to other operations running simultaneously (creating/destroying), we send and empty list of snapshots and get all known snapshots removed to the DB.

Caveats:

1) some FSs may not have snapshots enabled at all, so listing for them will always fail.
2) mounted snapshots are seen as regular FSs, listing for them will fail as well.

**Comment by jgrund** [comment]
Is there a different error code returned when the resource is busy?

**Comment by ip1981** [comment]
No, it's always 1 AFAIK

**Comment by jgrund** [comment]
so it's only the error string we can match on?

**Comment by ip1981** [comment]
> so it's only the error string we can match on?

Yes.

**Comment by jgrund** [comment]
yeah:

```
lctl snapshot_list -F zfsmo
Can't lock the snapshot config file /etc/ldev.conf (1): Resource temporarily unavailable
[root@mds1 ~]# echo $?
1
```

**Comment by jgrund** [comment]
Sounds like that's what we should do then.

**Comment by ip1981** [comment]
At least the "Resource temporarily unavailable" message must be stable enough :)

**Comment by jgrund** [comment]
Replaced by #2364
