### ISSUE TITLE
Mount clients on storage servers in integration tests

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#2255]
We are currently using a separate client node to mount lustre clients. While this is how it's been done traditionally, we can save time in the integration tests by mounting the filesystem on each of the storage servers using clush:

```
clush -g storage mkdir -p /mnt/fs
clush -g storage mount -t lustre 10.73.20.11@tcp0:10.73.20.12@tcp0:/fs /mnt/fs
```

By doing this, there will no longer be a need to spin up a client and install the lustre client software on it.

**Comment by mkpankov** [comment]
I think it could create disparity in how we test vs. how it's used in real life.

**Comment by jgrund** [comment]
It already is not how we are using it in real life. Going forward the most likely scenario is to use clients that are mounted on storage servers instead of requiring external servers.
