### ISSUE TITLE
Fix intermittent clearing of snapshot table

### ISSUE THREAD

**Issue by mkpankov** [whamcloud/integrated-manager-for-lustre#2261]
https://github.com/whamcloud/integrated-manager-for-lustre/blob/master/iml-services/iml-snapshot/src/main.rs#L48-L90

The state between removal and insertion can be seen by other threads or applications.

We either should use a transaction, or delete only "to delete" rows.

**Comment by ip1981** [comment]
https://github.com/whamcloud/integrated-manager-for-lustre/issues/2248 ?

**Comment by mkpankov** [comment]
Correcting myself here: it already deletes only rows that aren't present in next state update. But we can observe a situation where "to delete" rows were already deleted, but "to update" rows weren't yet updated. So the solution will be a transaction.

**Comment by jgrund** [comment]
Fixed by #2277
