### ISSUE TITLE
Update the limit param in graphql api's

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#2268]
Currently, the `limit` param allows you to specify a limit when retrieving items back from an API call. This is a numeric value that can be passed in but in some cases, we may want all results. To address this, postress allows us to pass in `ALL` instead of a numeric value, which is effectively the same as not passing a limit at all. Update all of the graphql API endpoints such that if `None` is passed in it will pass `ALL` to the LIMIT clause in the query. This will allow us to get all entries without modifying the existing api.

**Comment by jgrund** [comment]
Important invariant is that the API params stay the same type, i.e. limit is still an int.

**Comment by ip1981** [comment]
Could it be `Option<i32>`?

**Comment by johnsonw** [comment]
Currently, it is already an Option<i32> but if `None` is passed in it uses `unwrap_or(20)`.
