### ISSUE TITLE
Make it possible to have IML CLI under different names

### ISSUE THREAD

**Issue by ip1981** [whamcloud/integrated-manager-for-lustre#2295]
1. Make help text more neutral (avoid "IML")
2. Make generic description configurable / automatic:
```
foo 0.3.0
The Foo Bar for All CLI
```
3. A symbolic link or a shell wrapper might work just fine, shipped in a separate package:

![Screenshot_2020-10-01_19-03-22](https://user-images.githubusercontent.com/131844/94840507-cb366d00-0418-11eb-9f2b-b2e258ba056a.png)

**Comment by jgrund** [comment]
After symlinking it appears that the iml is still there for the version. Is there any way to make that configurable?

![Uploading Screen Shot 2020-10-02 at 12.43.10 PM.png…]()
