### ISSUE TITLE
IML and Lustre version Matrix , CetnOS/RHEL7.5.1804 || Question

### ISSUE THREAD

**Issue by atulyadavtech** [whamcloud/integrated-manager-for-lustre#2322]
Hi Team,

Please provide the compatible version of IML and Lustre With CentOS 7.5.1804.

Thank You
Atul Yadav
Locuz

**Comment by utopiabound** [comment]
The current version matrix is in the Online Help: [Release History](https://whamcloud.github.io/Online-Help/docs/Release_History.html)
