### ISSUE TITLE
limit scanning to physical devices on passive nodes

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#249]
Currently, we scan physical and logical (i.e. ZFS, LVM, MD, etc.) devices on all nodes.  The latter is really unnecessary and runs into concurrency/coherency problems.  It is unsafe for example to `zfs import` a pool, even _read-only_ on a host while another host has it imported.

But once we have determined that the physical devices on one node are available on another node we can assume that any logical devices are available on both nodes also and avoid having to scan for them on both nodes.  Scanning can be limited to a/the node that has active control of such devices, such as the node that has `zfs import`ed a pool.  Anything found there can be assumed to be present/valid for a node that has the same devices but is acting passive towards them.

The manager could either duplicate the (logical) device entries for such "equal" nodes as they are discoverd and/or change on the active node, or the database could be [re-]structured to only have a node-independent single copy of such logical device elements and then "link" them to their physical devices entries and/or nodes in the database.

**Comment by jgrund** [comment]
The biggest issue to think about here is how does this work without a manager. 

We want to move away from the manager being the single source of truth. In this scenario, we'll need the nodes to communicate in a more peer to peer fashion.

**Comment by brianjmurrell** [comment]
> We want to move away from the manager being the single source of truth. In this scenario, we'll need the nodes to communicate in a more peer to peer fashion.

Yes, I had considered this possibility also but was not sure of what actual use-cases would exist.

Consider the one use-case, perhaps, of storage servers that instead of being told how to configure Pacemaker by the manager configure pacemaker themselves based on what they discover for resources locally.  Even in such a scenario, the passive node doesn't actually need to know what the logical devices are since the active node can/will do the all of the Pacemaker resource configuration which will be shared with the passive node naturally through the CIB distribution mechanism.

The active node will still need to know which nodes are it's peers -- which have the same physical devices though, so that would indicate some peer-to-peer knowledge of shared physical devices at least.

Or, an interesting alternative scenario is that the active node configures Pacemaker with itself as a node that serves all of the physical/logical resources it can discover locally.  The passive node then matches what it discovers locally in terms of physical devices and then updates the configuration to make itself an additional node that can serve the physical and logical resources added by the active node.

In this way, the nodes actually use Pacemaker as their (i.e. peer-to-peer) sharing mechanism rather than an additional protocol needed to be utilised.

**Comment by jgrund** [comment]
> Currently, we scan physical and logical (i.e. ZFS, LVM, MD, etc.) devices on all nodes. The latter is really unnecessary and runs into concurrency/coherency problems. It is unsafe for example to zfs import a pool, even read-only on a host while another host has it imported.

We have basically implemented this for ZFS. Instead of importing + querying, we only receive ZED events for the active node and use the device-aggregator on the manager side to resolve shared pools / datasets.

LVM / MD have been handled transparently by device-scanner so far.
