### ISSUE TITLE
iml_sos_plugin needs to Obsoletes: chroma-diagnostics

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#362]
When _iml_sos_plugin_ is installed _chroma-diagnostics_ should be removed.

This can be done with:

```
Obsoletes: chroma-diagnostics
```

in the _iml_sos_plugin_ RPM.

**Comment by jgrund** [comment]
Done in:

https://github.com/whamcloud/iml_sos_plugin/blob/5b523bfc605fafbca5dd6e6b6781063e44fad74c/python-iml_sos_plugin.spec#L22
