### ISSUE TITLE
Complete excise of repos/bundles

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#368]
Because of the new deployment model of IML in 4.0.0.0 the concept of bundles (which become local repos) is deprecated.

Some of this deprecation happened in 4.0.0.0.  It should be completed.  To do this we need to hoist the package(-that-effects-the-profile) concept in profiles up to the top-level instead of being a child of bundles.

**Comment by utopiabound** [comment]
Will be addressed by work on Issue #799
