### ISSUE TITLE
create a facility for test code to update github issues

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#37]
Our [_fetch_help()](https://github.com/intel-hpdd/intel-manager-for-lustre/blob/007a4cb48081270b04a85e77c6cb66d70982d648/chroma-manager/tests/integration/core/utility_testcase.py#L183-L235) might be more useful if it posted to github issues instead of e-mailing people.

It would help with transparency and understanding the frequency of issues that we don't quite know the cause of yet.

**Comment by jgrund** [comment]
This is a good idea, but is unlikely to happen.
