### ISSUE TITLE
Separate remaining chroma-* modules

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#382]
Currently chroma-{agent,manager,...} are being built under a single repository.  These should be separated out into individual components/modules.

Once that is done, they should be built in Copr and installation should fetch them from there rather than being delivered in a/the tarball.

This will be necessary before we can completely remove bundles.

**Comment by brianjmurrell** [comment]
Tasks needed to be completed to complete this ticket:
- [ ] create PRs to separate chroma-agent into an [iml-agent repo](https://github.com/intel-hpdd/iml-agent/)
  - [ ] create a [manager-for-lustre-dependencies subdir](https://github.com/intel-hpdd/manager-for-lustre-dependencies/tree/chroma-agent) for it so that it can be built by Copr
  - [ ] test that it can be present in an enabled repo on the agent and co-exist with an existing iml-agent repo being served by a manager when:
    - [ ] superior to the version being served by the manager
    - [ ] inferior to the version being served by the manager
  - [ ] configure a package in [our Copr project](https://copr.fedorainfracloud.org/coprs/managerforlustre/manager-for-lustre/)
  - [ ] land iml-agent repo PRs and publish the module
  - [ ] land manager-for-lustre-dependencies PR

**Comment by brianjmurrell** [comment]
> test that it can be present in an enabled repo on the agent and co-exist with an existing iml-agent repo being served by a manager when [an] "inferior to the version being served by the manager"

This fails.  This means that we MUST push out a chroma-agent module that will be superior to any installation in the field that will still have an iml-agent repo on it's manager, and that any subsequent release of chroma-manager must NOT provide an iml-agent [repo that is allowed to jump ahead of the iml-agent that is in Copr].

This is most easily and certainly achieved by pushing a new release of chroma-manager that effects this iml-agent repo removal very shortly following to the iml-agent showing up in Copr.

**Comment by brianjmurrell** [comment]
Remaining work here is to strip away the cruft in the intel-manager-for-lustre repo to turn it into a stand-alone module.  This means no more building of a "tarball" for distribution and installation of the manager is done as a `yum` command once repos are set up.

This means dropping the chroma-dependencies/ directory completely.  I suspect there is nothing of use in there currently.

chroma-bundles/ will also be dropped and the profiles in the chroma-bundles/ directory need moving into the iml-manager RPM.  Same for the `create_installer` tool.  But really, ideally that should just go away in favour of meta-packages.

The `Makefile` will need completely gutting and remade into a standard _module-tools_ _Makefile_.

Documentation will need a rework to cover the necessary repo configuration as a prerequisite to the `yum` command installation method.

**Comment by jgrund** [comment]
> chroma-bundles/ will also be dropped and the profiles in the chroma-bundles/ directory need moving into the iml-manager RPM. Same for the create_installer tool. But really, ideally that should just go away in favour of meta-packages.

Can you expand on this? How would meta-packages cover current use-cases of bundles?

**Comment by brianjmurrell** [comment]
Sorry for conflating.  I mean that meta-packages should eliminate the need for `create_installer` and the install scripts it creates.  There was a time when those install scripts actually did work beyond installing packages but that's about all they do any more and meta-packages with the correct dependencies can do that.

**Comment by jgrund** [comment]
ah. Still, why would this need to be a meta-package rather than just part of the spec?

**Comment by jgrund** [comment]
This has been done in https://github.com/whamcloud/lustre-ldiskfs-zfs/pull/8
