### ISSUE TITLE
Remove concept of bundles

### ISSUE THREAD

**Issue by brianjmurrell** [whamcloud/integrated-manager-for-lustre#383]
Now that everything comes from external repositories and once the final packages to be [moved Copr](https://github.com/intel-hpdd/intel-manager-for-lustre/issues/382)  is complete, we can retire the concept of bundles/repos.

**Comment by jgrund** [comment]
We need to make sure we support existing users of bundles who are using them to skip Lustre installs, (I.E. they already have Lustre on the node, and do not want to install / rebuild or add ZFS).

**Comment by jgrund** [comment]
This will probably slip from 4.1

**Comment by utopiabound** [comment]
This will be addressed by work for #799
