### ISSUE TITLE
Don't have separate structures for zfsvols and zfsdatasets

### ISSUE THREAD

**Issue by tanabarr** [whamcloud/integrated-manager-for-lustre#400]
Given a _zvol_ is just a _zfs dataset_ of type `volume` as opposed to the default 'filesystem`, and the essential difference is that the former has a "reservation" property set, why don't we store them both as _datasets_ rather than having separate structures?

This makes sense to discuss now as we are re-architecting the agent to use the _device-scanner_ and filtering information from _zed_ events. The only difference visible in _zed_ events between creating a _dataset_ and _zvol_ is the setting of the `refreservation` property:

It should be noted that they do have different property sets.

**Comment by tanabarr** [comment]
IML treats ZfsDatasets as not usable_for_lustre but ZfsVols as usable_for_lustre (as they are intended to be block devices)
I suggest we store both as datasets in the device-scanner, and then differentiate in the agent based on the presence of the dataset _reservation_ property and/or _type_ property.

**Comment by tanabarr** [comment]
approach confirmed as reasonable by @jgrund

**Comment by jgrund** [comment]
In the manager, note if dataset is of type `filesystem` or `volume`, ex:

```[ { name: 'mgs/ds1', kind: 'volume' } ] ```

**Comment by jgrund** [comment]
Need to add kind to device-scanner

**Comment by jgrund** [comment]
Investigate + implement ways of getting current dataset / zvol sizes as well.
