### ISSUE TITLE
Server page shows updates still available for agent nodes after upgrading from 3.1.1.0 to 4.0.x 

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#455]
### Description 
After upgrading from 3.1.1.0 to 4.0.3 I noticed the server page shows that updates are still available, even though I updated them manually. Please see https://github.com/intel-hpdd/intel-manager-for-lustre/issues/442  for results of the upgrade.

### Repro
Upgrade from 3.1.1.0 to 4.0.3 using the instructions here: https://intel-hpdd.github.io/Online-Help/docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.html. After upgrading each of the storage nodes, go to the server page and you will see that each of the servers is showing that updates are still available.

### Version

What version of IML? Upgrade from 3.x to 4.x
What Operating System? CentOS
What Operating System version? EL 7.3 -> EL 7.4

**Comment by jgrund** [comment]
This should be fixed by the introduction of: https://github.com/whamcloud/iml-update-check
