### ISSUE TITLE
IML Status alerts report wrong timestamp

### ISSUE THREAD

**Issue by wutaizeng** [whamcloud/integrated-manager-for-lustre#462]
### Description 

IML Dashboard display correct timestamp (e.g 2018-01-31 13:43:44), but Status alert report wrong timestamp (e.g: 2018-01-30 21:43:53)

### Repro

N/A

### Version

What version of IML?

4.0.0.0

What Operating System?

RHEL

What Operating System version?

7.4

**Comment by brianjmurrell** [comment]
Are your machines' times in sync?

**Comment by johnsonw** [comment]
Is this related to https://github.com/intel-hpdd/GUI/issues/48?

**Comment by jgrund** [comment]
Hi @wutaizeng,

In addition to the above questions, are you expecting to see your timestamps in UTC or local time?

**Comment by wutaizeng** [comment]
I expect to see my timestamp in local time for "IML Status" report.

**Comment by wutaizeng** [comment]
@johnsonw Yes

**Comment by jgrund** [comment]
@wutaizeng We've scoped this feature (https://github.com/intel-hpdd/GUI/issues/48) into an upcoming release. We'll update this ticket once it has landed.

**Comment by jgrund** [comment]
Fixed in: https://github.com/whamcloud/GUI/issues/48 && https://github.com/whamcloud/GUI/pull/127
