### ISSUE TITLE
RabbitMQ fails to come up after reboot of IML node

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#480]
### Description 

After shutting down all systems, and then bringing them back up, rabbitMQ fails to start:
```
rabbitmq-server.service: Got notification message from PID 1204, but reception only permitted for main PID 1151
```

[sosreport-ieel-mgr2-20180226120949.tar.gz](https://github.com/intel-hpdd/intel-manager-for-lustre/files/1759603/sosreport-ieel-mgr2-20180226120949.tar.gz)

And thus the whole filesystem fails to start

```
[root@ieel-mgr2 ~]# chroma-config restart
Stopping daemons
Starting daemons
Some services failed to start: corosync, http_agent, job_scheduler, plugin_runner, syslog
Traceback (most recent call last):
  File "/usr/bin/chroma-config", line 10, in <module>
    load_entry_point('chroma-manager==4.0.3.0', 'console_scripts', 'chroma-config')()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 898, in chroma_config
    service_config.start()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 609, in start
    self._start_services()
  File "/usr/share/chroma-manager/chroma_core/lib/service_config.py", line 333, in _start_services
    raise RuntimeError(msg)
RuntimeError: Some services failed to start: corosync, http_agent, job_scheduler, plugin_runner, syslog
```

### Repro

Power off all systems, then power them back up.

### Version

What version of IML? 4.0.3
What Operating System? CentOS
What Operating System version? 7.4

### Workaround

Restart rabbitmq manually, then restart chroma-config
```
# systemctl restart rabbitmq-server.service
# chroma-config restart
```

**Comment by jgrund** [comment]
Have you see this more than once as well?

**Comment by utopiabound** [comment]
I think it was a hard reboot.  I have seen this more than once, but I think I wrote it off the first time.

**Comment by jgrund** [comment]
This is still an issue. 

I've tried using `NotifyAccess=all` in the `rabbitmq-server.service` but that leads to another issue. 

I think this may be something to be fixed in the upstream rabbitmq-server RPM
