### ISSUE TITLE
IML GUI non-functional with JS disabled

### ISSUE THREAD

**Issue by Zubrania** [whamcloud/integrated-manager-for-lustre#499]
### Description 

A short description of your issue
After successfully  completed installation  no  gui  interface  available on  https://hostname/ui
The only information which  confirms that IML service  is runinng is  a page header 

```html
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <base href="/ui/" />

  <title>Intel&reg; Manager for Lustre* software</title>

  <link rel="icon" href="/gui/source/intel.ico" />

  <script type="text/javascript">
```

nginx is available at http://hostname
### Repro

What steps were taken leading to this issue
Fresh installation 
### Version

What version of IML?
IML-4.0.3.0
What Operating System?
CentOS
What Operating System version?
7.4 with  latest updates and fence-agents package from RHEL 7.4

**Comment by brianjmurrell** [comment]
Can you attach the result of an [iml-diagnostics](https://intel-hpdd.github.io/Online-Help/docs/Errors_Troubleshooting_12_0.html#12.2) from the manager node?

**Comment by Zubrania** [comment]
Hello  Brian   sorry  for the  update. The problem was connected with  javascript restriction.Thank you for your help

**Comment by brianjmurrell** [comment]
@jgrund: Can we add something to the GUI that tells people to turn on JS if it's not enabled via a `<noscript>` tag?

**Comment by brianjmurrell** [comment]
@Zubrania: Thanks much for the update.  It helps us to know how people resolve issues even if they resolve them themselves.

**Comment by jgrund** [comment]
@brianjmurrell Yes. It should be very trivial to do actually if someone wants to take a crack at it.

Just need to a dd `<noscript>` plus some simple markup explaining JS must be enabled to use the GUI. All that can be added here:

https://github.com/intel-hpdd/GUI/blob/ebf8f9d6b02c59558fcb6257d7f58cd78b3475b8/index.ejs#L34

**Comment by jgrund** [comment]
This is unlikely to be addressed in the near term.
