### ISSUE TITLE
Clarify naming of test utility classes

### ISSUE THREAD

**Issue by tanabarr** [whamcloud/integrated-manager-for-lustre#590]
Currently it's not clear from looking at the file structure, which utility classes such as `ApiTestCaseWithReset` and `ChromaIntegrationTestCase` are used in which type of "Integration" test (EFS or SSI). These 2 classes are actually only used in SSI so should be moved further down the folder hierarchy and possibly renamed. Other naming changes and directory organisation would also help clarify what makes up EFS and SSI.

**Comment by brianjmurrell** [comment]
Even though they might not be currently used by EFS, could they be?  Is there anything that is SSI specific about them?  Could they be used by some newly written integration test?
