### ISSUE TITLE
IML / dnf / rhnplugin

### ISSUE THREAD

**Issue by jbs344** [whamcloud/integrated-manager-for-lustre#683]
### Description 

IML (version 4.0.6.0 and earlier versions) uses dnf to install the lustre rpms.  We use a local redhat satellite server, so dnf needs to load the rhnplugin enabled before they will see any valid repos.  Is it possible to make the loading of the rnplugin a user selectable option?

### Repro

Working backward from an install of ee 4.0.6.0 that consistantly failed the repo checks despite being subscribed to the relevant satellite channels.

### Version

What version of IML?  4.0.6.0
What Operating System? RHEL
What Operating System version? 7.5

### iml-diagnostics

not required

**Comment by jgrund** [comment]
Hi @jbs344,

We have dropped dnf as a dep in our next major version, so this should no longer be a problem there.
