### ISSUE TITLE
Production IML install in monitoring mode

### ISSUE THREAD

**Issue by UnknownNet** [whamcloud/integrated-manager-for-lustre#698]
### Description 

I have a system that is already in production and want to install IML in monitoring mode. The "new server" addition attempts to "yum update" and install a number of packages; is there any method for disabling all of this? I understand chroma-agent needs to be installed, but does the rest need to be upgraded as well?

**Comment by jgrund** [comment]
Hey @UnknownNet,

Can you elaborate on the yum update you are seeing? I am trying this on a 4.1 preview and am not seeing a yum update performed for a monitor mode install.

**Comment by UnknownNet** [comment]
I have lustre servers installed at a specific CentOS version running in
production. When I attempt to configure them in IML as monitored (not
managed) IML looks to install chroma-agent, but prior to this there is a
check on yum along with what appeared to be a yum update (lots of changes
in the yum log).

The worry here is how to configure a running system with minimal impact
into monitored mode in IML.

**Comment by jgrund** [comment]
Ok, got it. 

We can make that configurable; of course any direct dependencies of the iml-agent may be updated if they are pinned to newer versions of what is currently installed.

**Comment by UnknownNet** [comment]
I think that would work. Thanks.

**Comment by UnknownNet** [comment]
I was wondering if this has been made configurable or if there's an
expectation when it might be. Thanks.

**Comment by jgrund** [comment]
@UnknownNet, sorry for the delay; we've decided to remove the updating during an IML install. It has landed in https://github.com/whamcloud/iml-agent/commit/6667bfa789a2f817fbfb13a2867938aff7ef9933, and will be shipped in the upcoming 4.1 release.
