### ISSUE TITLE
chroma_core_volumenode table is unnecessarily being populated continuously

### ISSUE THREAD

**Issue by indivarnair** [whamcloud/integrated-manager-for-lustre#710]
### Description 

IML is continuously populating chroma_core_volumenode table with duplicate information.
There are only 36 OST across 6 OSS (i.e. 6 OST per OSS).
But over time, the table has grown to multiple GBs, making IML interactions extremely slow.

Unnecessary entries like device links in '/dev/disk/by-path' are also added to the table.

### Repro

Nothing specific needs to be done to reproduce the issue.
It happens automatically.

### Version

What version of IML? 
IML 3.1.1.0  (Part of IEEL ee-3.1.1.0)

What Operating System? 
CentOS

What Operating System version? 
7.3

### iml-diagnostics

The chroma_core_volumenode table is a few GBs big, so here are a few entries. Hope it helps - 

COPY chroma_core_volumenode (id, volume_id, host_id, path, storage_resource_id, "primary", use, not_deleted) FROM stdin;
27	26	6	/dev/mapper/mpathj	383	t	t	t
55	25	5	/dev/mapper/mpathc	649	t	t	t
26	25	6	/dev/mapper/mpathc	382	f	t	t
758479	24	5	/dev/disk/by-path/pci-0000:0d:00.1-fc-0x50060e801013b992-lun-11	\N	f	f	\N
841117	15	6	/dev/disk/by-path/pci-0000:0c:00.1-fc-0x50060e801013b998-lun-4	\N	f	f	\N
50	18	5	/dev/mapper/mpathe	640	t	t	t
758480	26	5	/dev/disk/by-path/pci-0000:08:00.0-fc-0x50060e801013b997-lun-10	\N	f	f	\N
31	18	6	/dev/mapper/mpathe	391	f	t	t
51	26	5	/dev/mapper/mpathj	641	f	t	t
1592565	19	5	/dev/disk/by-path/pci-0000:0c:00.0-fc-0x50060e801013b99e-lun-7	\N	f	f	\N
2457	16	5	/dev/disk/by-path/pci-0000:0d:00.1-fc-0x50060e801013b992-lun-6	\N	f	f	\N
2130	18	6	/dev/disk/by-path/pci-0000:0d:00.1-fc-0x50060e801013b990-lun-5	\N	f	f	\N
1699	9	3	/dev/disk/by-id/wwn-0x60060e8010145b30058b458300000001	\N	f	f	\N
1987	23	5	/dev/disk/by-path/pci-0000:08:00.1-fc-0x50060e801013b993-lun-8	\N	f	f	\N
.
.
.
2866079	50	9	/dev/disk/by-path/pci-0000:0d:00.1-fc-0x50060e8010145a92-lun-8	\N	f	f	\N
2866080	50	9	/dev/disk/by-path/pci-0000:0d:00.0-fc-0x50060e8010145a96-lun-8	\N	f	f	\N
2866081	46	9	/dev/disk/by-path/pci-0000:0d:00.1-fc-0x50060e8010145a92-lun-9	\N	f	f	\N
2866082	44	9	/dev/disk/by-path/pci-0000:07:00.1-fc-0x50060e8010145a9b-lun-11	\N	f	f	\N
2866083	45	9	/dev/disk/by-path/pci-0000:0d:00.0-fc-0x50060e8010145a96-lun-5	\N	f	f	\N
2866084	40	9	/dev/disk/by-path/pci-0000:08:00.1-fc-0x50060e8010145a93-lun-2	\N	f	f	\N
2866118	45	9	/dev/disk/by-path/pci-0000:08:00.1-fc-0x50060e8010145a93-lun-5	\N	f	f	\N
2866119	45	9	/dev/disk/by-path/pci-0000:0c:00.1-fc-0x50060e8010145a9a-lun-5	\N	f	f	\N
2866120	50	9	/dev/disk/by-path/pci-0000:08:00.1-fc-0x50060e8010145a93-lun-8	\N	f	f	\N
2866121	48	9	/dev/disk/by-path/pci-0000:0d:00.0-fc-0x50060e8010145a96-lun-3	\N	f	f	\N
2866122	43	9	/dev/disk/by-path/pci-0000:0c:00.1-fc-0x50060e8010145a9a-lun-6	\N	f	f	\N
2866123	49	9	/dev/disk/by-path/pci-0000:08:00.1-fc-0x50060e8010145a93-lun-10	\N	f	f	\N
2866124	39	9	/dev/disk/by-path/pci-0000:0c:00.0-fc-0x50060e8010145a9e-lun-7	\N	f	f	\N
2866125	48	9	/dev/disk/by-path/pci-0000:08:00.0-fc-0x50060e8010145a97-lun-3	\N	f	f	\N
2866126	41	9	/dev/disk/by-path/pci-0000:0c:00.1-fc-0x50060e8010145a9a-lun-1	\N	f	f	\N
2866127	40	9	/dev/disk/by-path/pci-0000:0d:00.0-fc-0x50060e8010145a96-lun-2	\N	f	f	\N
2866128	46	9	/dev/disk/by-path/pci-0000:0c:00.0-fc-0x50060e8010145a9e-lun-9	\N	f	f	\N
2866129	50	9	/dev/disk/by-id/wwn-0x60060e8010145a90058b457900000008	\N	f	f	\N
2866130	42	9	/dev/disk/by-path/pci-0000:08:00.1-fc-0x50060e8010145a93-lun-4	\N	f	f	\N

### Solution Required

1. How do we disable this continuous scanning of volumes on the lustre nodes?
2. What is a safe way to delete all entries other than the 36 - /dev/mapper/mpathX entries -
    Should a simple SQL delete query on the table do?
    Do we need to delete some related entries in some other tables too?
    Are there any files that needs to be deleted too?

**Comment by jgrund** [comment]
Hi @indivarnair,

The Github issue tracker is for issues relating to the open source versions of IML (4.x+).

Please go through support channels if you would like help with older versions.
