### ISSUE TITLE
IML 5.0 Manual testing

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#720]
Perform manual testing for IML 5. We should cover:

- [x] monitor mode ldiskfs
- [x] managed mode ldiskfs
- [x] monitor mode zfs
- [x] managed mode zfs
- [x] managed mode ldiskfs (patchless) 
- [x] managed mode zfs (patchless)
- [x] managed mode using fqdn for server names (Just add servers and verify corosync is configured properly)
- [x] upgrade from 4.0.1
- [x] upgrade from 4.0.10

**Comment by johnsonw** [comment]
Testing results can be found here: #906

**Comment by jgrund** [comment]
@johnsonw Can we close this?

**Comment by johnsonw** [comment]
I think we're good to close this now. I will do an additional set of testing once the preset patch lands.
