### ISSUE TITLE
Corosync error while installing lustre server modules via IML

### ISSUE THREAD

**Issue by jameslam0250** [whamcloud/integrated-manager-for-lustre#732]
We are using IML 4.0.8.0 as a GUI interface to deploy the lustre. During the process, the corosync error has been arisen from the interface and the information as follows.

What version of IML? 4.0.8.0
What Operating System? CentOS 7.5

while the error is captured below:
sbin/ip link set dev eno4 up: 0

/sbin/ip addr add 10.0.0.156/24 dev eno4: 0

/usr/bin/firewall-cmd --add-rich-rule=rule family="ipv4" destination address="226.94.0.1" protocol value="tcp" accept: 252

FirewallD is not running

/usr/bin/firewall-cmd --remove-rich-rule=rule family="ipv4" destination address="226.94.0.1" protocol value="tcp" accept: 252

FirewallD is not running

bash -c echo ******************** | passwd --stdin hacluster: 0
Changing password for user hacluster.
passwd: all authentication tokens updated successfully.

/usr/bin/firewall-cmd --add-port=37435/udp: 252

FirewallD is not running

/usr/bin/firewall-cmd --add-port=2224/tcp: 252

FirewallD is not running

systemctl start pcsd: 0

systemctl is-active pcsd: 0
active

systemctl enable corosync: 0

Created symlink from /etc/systemd/system/multi-user.target.wants/corosync.service to /usr/lib/systemd/system/corosync.service.

systemctl enable pcsd: 0

Created symlink from /etc/systemd/system/multi-user.target.wants/pcsd.service to /usr/lib/systemd/system/pcsd.service.

pcs cluster auth OSS2.ust.hk -u hacluster -p ********************: 0
oss2.ust.hk: Authorized

pcs cluster setup --name lustre-ha-cluster --force OSS2.ust.hk --transport udp --rrpmode passive --addr0 192.168.0.0 --mcast0 226.94.0.1 --mcastport0 37435 --addr1 10.0.0.0 --mcast1 226.94.1.1 --mcastport1 37435 --token 17000 --fail_recv_const 10: 1
Destroying cluster on nodes: OSS2.ust.hk...
OSS2.ust.hk: Unable to authenticate to OSS2.ust.hk - (HTTP error: 401), try running 'pcs cluster auth'
OSS2.ust.hk: Unable to authenticate to OSS2.ust.hk - (HTTP error: 401), try running 'pcs cluster auth'

Error: unable to destroy cluster
OSS2.ust.hk: Unable to authenticate to OSS2.ust.hk - (HTTP error: 401), try running 'pcs cluster auth'

iml-diagonsis report can be provided if needed

**Comment by johnsonw** [comment]
Hi @jameslam0250,

Have you tried running "pcs cluster auth" on OSS2? It's probably worth looking through the corosync and pacemaker information to see if there are any differences between the HA pairs.

Regards,

Will

**Comment by johnsonw** [comment]
Is it possible that another machine is communicating with OSS2? For example, if you are using vm's, could another vm be trying to access OSS2 as well? If so, multiple machines could be competing to talk to OSS2. This is one of the first errors that occurs in that scenario.

**Comment by jameslam0250** [comment]
We are currently building this storage system and that is the first OSS node we are going to install. So I guess there is no other machines competing each other

**Comment by johnsonw** [comment]
There may be an issue with the setup of your HA pair. Can you check the corosync configuration (/etc/corosync/corosync.conf) on both your oss1 and your oss2? Check to see if one may have an extra node, different mcast port, etc. Also, are you using two mds's as an HA pair? If so, were they able to configure properly?

**Comment by johnsonw** [comment]
Hi @jameslam0250,

Is there any chance you could setup a vagrant cluster with the version of IML you are installing and see if you run into the same problem? We have a repo that make setting up the cluster pretty simple: https://github.com/whamcloud/Vagrantfiles. Once you clone the repo, do the following:
1. navigate to repo and cd into the `iml-sandbox` directory
2. Run: `vagrant up iscsi adm mds1 mds2 oss1 oss2`
3. scp the IML tarball you are using to the `adm` node. Once it's been added, ssh into the adm node, extract the file, and run the install. IML should now be installed on the admin node.

Once you've done this, open your browser and navigate to `https://localhost:8443/ui/`. The webpage should load. Login with username `admin` and password `lustre`. Once logged in, navigate to `configuration->servers`. Click the button to add servers and in the input enter, `mds[1,2].local, oss[1,2].local`. Continue installing the servers from this point forward and see if you are running into the same issue.

**Comment by jameslam0250** [comment]
Do we need to remove all the modules/RPM/files from the IML and OSS and install this lustre via Vagrant?

We based on the tar zip build and install the lustre

**Comment by johnsonw** [comment]
The vagrant cluster should be completely separate from your current installation. You can do it on a single computer to test if you are able to recreate the issue.

**Comment by johnsonw** [comment]
No need to roll anything back. You can do it on another system if you would like. All you need is to install virtualbox and vagrant on any system and then follow the instructions I laid out above. The goal here is to see if you are able to re-create the issue in a separate vagrant cluster (if you are then we need to look and see what specifically is causing the issue as our manual testing did not encounter this problem). If the servers deploy successfully on the vagrant cluster you can then compare your actual cluster to the vagrant cluster and see what the difference is.

**Comment by jameslam0250** [comment]
and finally we find out that our DNS server uses small letters on the servers and we were using capital letters for the hostname for deployment.

and during the corosync setup the authentication rejects but small letters of hostname can authenticate correctly.
and everything goes smooth now
