### ISSUE TITLE
max_sectors_kb and max_hw_sectors_kb are not configurable in IML.

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#769]
### Description 

max_sectors_kb and max_hw_sectors_kb are not configurable in IML.

### Repro

The target details screen does not provide the ability to adjust these parameters after a filesystem is created:
![image](https://user-images.githubusercontent.com/1100657/50297877-d1c64100-044b-11e9-92ad-0f97078e7add.png)

### Version

All versions

**Comment by johnsonw** [comment]
I spoke with Oleg and he said that the max_sectors_kb is the one that can be configured for auto tune and that the max_hw_sectors_kb setting can be used as the high limit for the max_sectors_kb.

**Comment by jgrund** [comment]
To implement: update tunefs for ldiskfs backed devices: set max_sectors_kb
