### ISSUE TITLE
Fix depsolving involving lustre / lustre-client

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#799]
When a package that is available in both lustre / lustre-client, is required by another package, yum is unable to depsolve to use lustre, even though lustre obsoletes lustre-client and yum should be able to account for it.

We need a way to install the right thing in these scenarios. We could use dnf (again) but the straightforward solution is to not send the lustre_client repo to storage servers.

This logic will need to be built into profiles, which further means adding the ability for remote repos to be specified in profiles (don't think we have that now).

**Comment by utopiabound** [comment]
lustre-client < VERSION is obsoleted by lustre rpm.  So an old client will be obsoleted by a current lustre rpm, but not a current client.
It would be best to use separate repos for lustre and lustre-client

**Comment by jgrund** [comment]
Is there an advantage to obsoleting only older versions?

**Comment by utopiabound** [comment]
For change to < vs <= see [LU-9776](https://jira.whamcloud.com/browse/LU-9776)
lustre-client becomes uninstallable if the obsoletes applies to same version with both lustre and lustre-client repos installed.

With regards to depsolve of lustre vs. lustre-client rpms.
lustre rpm provides lustre-client (added by [LU-7228](https://jira.whamcloud.com/browse/LU-7228)) because technically it's true that lustre package does provide everything you need for lustre-client access.

**Comment by utopiabound** [comment]
**Proposed Fix**
Make "default" repo list smaller:
* IML repo (Copr repo containing iml-agent rpms)
* EPEL (needed by agent)
Rename `storage_server.repo` to `default.repo`

Add repofile-list to profiles:
Each repofile in list will be NAME.repo

So `base_managed.profile` would contain a repolist: (_file contents in-line_)
* lustre-server
```
[lustre]
name=Lustre Server
baseurl=https://downloads.whamcloud.com/public/lustre/lustre-2.12.0/el7/server/
enabled=1
gpgcheck=0

[e2fsprogs]
name=Lustre e2fsprogs
baseurl=https://downloads.whamcloud.com/public/e2fsprogs/latest/el7/
enabled=1
gpgcheck=0
```

Whereas `posix_copytool_worker.profile` would reference only repo file:
* lustre-client

New `posix_copytool_worker.profile`:
```
{
  "ui_name": "POSIX HSM Agent Node",
  "managed": true,
  "worker": true,
  "name": "posix_copytool_worker",
  "initial_state": "working",
  "ntp": true,
  "corosync": false,
  "corosync2": false,
  "pacemaker": false,
  "bundles": [
    "external"
  ],
  "ui_description": "An HSM agent node using the POSIX copytool",
  "packages": {
    "external": [
      "python2-iml-agent-management",
      "lustre-client"
    ]
  },
  "repolist": [
    "lustre-client"
  ]
}
```

**Comment by jgrund** [comment]
> * Rename `storage_server.repo` to `default.repo`

Maybe `base.repo`? Then it could be included in the repolist like lustre / lustre-client

**Comment by utopiabound** [comment]
Okay.  `base.repo` and it will be in the `repolist`
