### ISSUE TITLE
Collect + display ZFS statistics

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#801]
IML provides monitoring of standard Lustre statistics but this could be extended to provide the administrator more insight into what is happening at the ZFS layer.

An incomplete list:

- Request size historgrams: `zpool iostat -r`
- Latency histograms `zpool iostat -l`
- Queue stats `zpool iostat -q`
- SMART stats `zpool iostat|staus -c smart,smartx (or any of the misc stats from zpool iostat|status -c)`
- checking scrub status/stats.

**Comment by utopiabound** [comment]
Also:
* ARC stats (c.f. [arcstat.py](https://github.com/zfsonlinux/zfs/blob/master/cmd/arcstat/arcstat) from ZFS)
* Resilver status
