### ISSUE TITLE
Host has no NIDS 

### ISSUE THREAD

**Issue by ldd91** [whamcloud/integrated-manager-for-lustre#804]
### Description 

A short description of your issue
i using iml-4.0.9.0 to monitor existing lustre file-system. While running detect file system it is throwing an error host mds has no NIDS. The lustre file system is working fine and we able to do lctl ping to all mds, oss and client nodes. The job_scheduler.log shows:
File "/usr/share/chroma-manager/chroma_core/lib/detection.py" line 169,in learn_primary_target
raise NoNidsPresent ("Host %s has no NIDS!" % tm.host)
### Repro

What steps were taken leading to this issue

### Version

What version of IML?4.0.9.0
What Operating System?centos7
What Operating System version?

### iml-diagnostics

Attach any [`iml-diagnostics`](https://whamcloud.github.io/Online-Help/docs/Errors_Troubleshooting_12_0.html#12.2) for nodes relevant to this issue.

**Comment by ldd91** [comment]
The chroma_agent.log shows:
daemon WARNING get_nids: failed to open

**Comment by johnsonw** [comment]
Hi @ldd91,

Can you try restarting the agent on the server nodes and attempt to re-detect the filesystem?
You should be able to do this on each server by running:
```
systemctl restart chroma-agent
```

Regards,

Will

**Comment by ldd91** [comment]
Thanks for your timely reply,but after i restarted the agent,the job_scheduler.log still shows found no NIDS

**Comment by johnsonw** [comment]
Ok, next, let's try restarting the chroma-manager on the manager node:
```
chroma-config restart
```

**Comment by jgrund** [comment]
@ldd91 Is this ok to close?

**Comment by ldd91** [comment]
It was caused by VIP in my cluster,i will close it.
