### ISSUE TITLE
Host has no NIDS

### ISSUE THREAD

**Issue by ldd91** [whamcloud/integrated-manager-for-lustre#805]
i using iml-4.0.9.0 to monitor existing lustre file-system. While running detect file system it is throwing an error host mds has no NIDS. The lustre file system is working fine and we able to do lctl ping to all mds, oss and client nodes. The job_scheduler.log shows:
File "/usr/share/chroma-manager/chroma_core/lib/detection.py" line 169,in learn_primary_target
  raise NoNidsPresent ("Host %s has no NIDS!" % tm.host)

**Comment by jgrund** [comment]
Dup of #804
