### ISSUE TITLE
Error when configuring a monitored node

### ISSUE THREAD

**Issue by cvoltz** [whamcloud/integrated-manager-for-lustre#827]
### Description

When attempting to configure a node, at the step where it is trying to install the `iml-agent` bundle, a traceback is shown in the log 3 times:
```
dnf clean all --disablerepo=* --enablerepo=e2fsprogs --enablerepo=epel --enablerepo=iml-agent --enablerepo=lustre --enablerepo=lustre-client --enablerepo=managerforlustre-manager-for-lustre --enablerepo=ngompa-dnf-el7: 1

Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python2.7/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python2.7/site-packages/dnf/base.py", line 29, in <module>
    import libdnf.transaction
  File "/usr/lib64/python2.7/site-packages/libdnf/__init__.py", line 3, in <module>
    from . import conf
  File "/usr/lib64/python2.7/site-packages/libdnf/conf.py", line 17, in <module>
    _conf = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/libdnf/conf.py", line 16, in swig_import_helper
    return importlib.import_module('_conf')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _conf
```
and the backtrace shows:
```
Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 316, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/host.py", line 702, in run
    updates_available = package.update(host, package_report)
  File "/usr/share/chroma-manager/chroma_core/models/package.py", line 85, in update
    for repo_name in repo_names.intersection(package_report):
TypeError: 'NoneType' object is not iterable
```

### Repro

1. Install Lustre 2.10.4 on CentOS 7.4 on the Lustre servers.
1. Install IML 4.0.6.0 on CentOS 7.4 on the IML server.
1. Add the Lustre servers in monitored mode by running this command (on the IML server) for each Lustre server (replace `server-name` with the actual server name):
     `chroma server-add server-name --server_profile base_monitored`
1. On the IML web page, select the `Servers` link (under `Resources`) to display the list of servers. All machines should be added and should match this state:
   * Server State: (green checkmark) No Issues
   * Profile: Monitored Storage Server
   * LNET State: Unconfigured (green checkmark)
   For example:
      ![Screenshot from 2019-03-19 10-07-19](https://user-images.githubusercontent.com/549284/54617228-e3a98700-4a2e-11e9-8818-7a6d156fc45a.png)
1. Click the `Actions` button for a server and select `Continue Server Configuration` (the tooltip will say `Install packages on this server`).
1. After a period of time, an error will be displayed: ![Screenshot from 2019-03-19 10-00-32](https://user-images.githubusercontent.com/549284/54617055-9f1deb80-4a2e-11e9-98bc-9b3bd6d2a256.png)
1. Click the `Install packages on server` link to see the details: ![Screenshot from 2019-03-19 10-00-56](https://user-images.githubusercontent.com/549284/54617066-a47b3600-4a2e-11e9-97fb-8ef559fba0db.png)
1. Click the `3/4 Installing packages` link to display the log: ![Screenshot from 2019-03-19 10-06-35](https://user-images.githubusercontent.com/549284/54617104-b4931580-4a2e-11e9-9fac-ffa19d0627a2.png)

### Version

What version of IML? 4.0.6.0
What Operating System? CentOS
What Operating System version? 7.4

### iml-diagnostics

Attach any [`iml-diagnostics`](https://whamcloud.github.io/Online-Help/docs/Errors_Troubleshooting_12_0.html#12.2) for nodes relevant to this issue.

[sosreport-cv-g9-mgs-2019-03-19-mscdubo.tar.gz](https://github.com/whamcloud/integrated-manager-for-lustre/files/2984310/sosreport-cv-g9-mgs-2019-03-19-mscdubo.tar.gz)

### Work-around

I determined that the problem was that some packages been installed or upgraded during the installation process which resulted in the wrong version of `dnf` and its dependencies being installed:
```
dnf-4.0.9.2-1.el7_6.noarch
dnf-data-4.0.9.2-1.el7_6.noarch
librepo-1.8.1-7.el7.x86_64
python2-dnf-4.0.9.2-1.el7_6.noarch
python2-hawkey-0.22.5-1.el7_6.x86_64
rpm-4.11.3-35.el7.x86_64
rpm-libs-4.11.3-35.el7.x86_64
rpm-build-4.11.3-35.el7.x86_64
rpm-build-libs-4.11.3-35.el7.x86_64
rpm-python-4.11.3-35.el7.x86_64
```

Running the following commands on each server resolved the issue and allowed the `iml-agent` bundle to be installed successfully (make sure any required proxy environment variables are already setup):
```
rpm --erase --nodeps --verbose \
  dnf \
  dnf-data \
  python2-dnf \
  python2-hawkey

yum downgrade -y \
  librepo-1.7.16-1.el7.x86_64 \
  rpm-4.11.3-25.el7.x86_64 \
  rpm-libs-4.11.3-25.el7.x86_64 \
  rpm-build-4.11.3-25.el7.x86_64 \
  rpm-build-libs-4.11.3-25.el7.x86_64 \
  rpm-python-4.11.3-25.el7.x86_64

yum install -y \
  python-librepo \
  rpm-plugin-systemd-inhibit

yum reinstall -y chroma-agent \
  --disablerepo=* \
  --enablerepo=e2fsprogs \
  --enablerepo=epel \
  --enablerepo=iml-agent \
  --enablerepo=lustre \
  --enablerepo=lustre-client \
  --enablerepo=managerforlustre-manager-for-lustre \
  --enablerepo=ngompa-dnf-el7
```

After the commands have been run:
1. From the IML web page, click on the `Actions` button for the server and select `Continue Server Configuration` and it will be setup without error.
1. Click `Close` to close the `Install packages` dialog box.
1. Click `Close` to close the `Commands` dialog box.
1. Click on the `Actions` button for the server and select `Setup monitored server` (the tooltip will say `Setup this monitored host`).
1. The `Commands` dialog box will show that the setup has `Succeeded`.
1. Clock `Close` to close the `Commands` dialog box and the `LNet State` will change to `LNet Up`. For example: 
![Screenshot from 2019-03-19 12-03-00](https://user-images.githubusercontent.com/549284/54626370-06dc3280-4a3f-11e9-8728-6ecce73300ac.png)

Here are the package versions which worked together:
```
rpm --query \
  chroma-agent \
  dnf \
  dnf-conf \
  dnf-data \
  dnf-plugins-core \
  hawkey \
  librepo \
  python-dnf-plugins-core \
  python-hawkey \
  python-librepo \
  python2-dnf \
  python2-hawkey \
  rpm \
  rpm-libs \
  rpm-build \
  rpm-build-libs \
  rpm-python \
  rpm-plugin-systemd-inhibit

chroma-agent-4.0.6.0-5034.el7.noarch
dnf-1.1.5-2.01.el7.centos.noarch
dnf-conf-1.1.5-2.01.el7.centos.noarch
package dnf-data is not installed
dnf-plugins-core-0.1.15-2.el7.centos.noarch
hawkey-0.6.2-1.el7.centos.x86_64
librepo-1.7.16-1.el7.x86_64
python-dnf-plugins-core-0.1.15-2.el7.centos.noarch
python-hawkey-0.6.2-1.el7.centos.x86_64
python-librepo-1.7.16-1.el7.x86_64
python2-dnf-1.1.5-2.01.el7.centos.noarch
package python2-hawkey is not installed
rpm-4.11.3-25.el7.x86_64
rpm-libs-4.11.3-25.el7.x86_64
rpm-build-4.11.3-25.el7.x86_64
rpm-build-libs-4.11.3-25.el7.x86_64
rpm-python-4.11.3-25.el7.x86_64
rpm-plugin-systemd-inhibit-4.11.3-25.el7.x86_64
```

**Comment by jgrund** [comment]
Thanks for the report @cvoltz. We have fixed this issue in IML 4.0.9

**Comment by jgrund** [comment]
I mistook this for a different issue. It appears the root cause here is just that the dnf that lives in CentOS Extras is not compatible with anything older than EL 7.6.

```
cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
[root@vm9 ~]# yum repolist
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.keystealth.org
 * extras: mirror.keystealth.org
 * updates: mirror.fileplanet.com
repo id                                                                               repo name                                                                                status
base/7/x86_64                                                                         CentOS-7 - Base                                                                          10,019
extras/7/x86_64                                                                       CentOS-7 - Extras                                                                           385
updates/7/x86_64                                                                      CentOS-7 - Updates                                                                        1,513
repolist: 11,917
[root@vm9 ~]# dnf
-bash: dnf: command not found
[root@vm9 ~]# yum install -y -q dnf
[root@vm9 ~]# dnf
Traceback (most recent call last):
  File "/usr/bin/dnf", line 57, in <module>
    from dnf.cli import main
  File "/usr/lib/python2.7/site-packages/dnf/__init__.py", line 30, in <module>
    import dnf.base
  File "/usr/lib/python2.7/site-packages/dnf/base.py", line 29, in <module>
    import libdnf.transaction
  File "/usr/lib64/python2.7/site-packages/libdnf/__init__.py", line 3, in <module>
    from . import conf
  File "/usr/lib64/python2.7/site-packages/libdnf/conf.py", line 17, in <module>
    _conf = swig_import_helper()
  File "/usr/lib64/python2.7/site-packages/libdnf/conf.py", line 16, in swig_import_helper
    return importlib.import_module('_conf')
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _conf
```

**Comment by jgrund** [comment]
So, the workaround here is to make sure to use the vault version of extras when installing / upgrading IML on an OS < EL7.6 and to disable the stock extras version before upgrading / installing.

**Comment by johnsonw** [comment]
Want me to update the upgrade docs to mention this?

**Comment by jgrund** [comment]
I'll add it as a known issue.

**Comment by brianjmurrell** [comment]
Does anyone happen to know exactly what needs to be updated to 7.6 to resolve this, short of upgrading the whole node?

**Comment by jgrund** [comment]
@brianjmurrell nope, haven't dug into the cause. We no longer use dnf for IML 5+. 

If you need an older version, there is one available here. https://copr.fedorainfracloud.org/coprs/managerforlustre/manager-for-lustre/package/dnf/

Anything < IML 4.0.10.x should use that repo and pull in the corresponding dnf (provided 7.6 extras isn't enabled).

**Comment by szsahin** [comment]
> 
> 
> I mistook this for a different issue. It appears the root cause here is just that the dnf that lives in CentOS Extras is not compatible with anything older than EL 7.6.

After installing/updating some related packages, resolved the **"ImportError: No module named _conf"** issue for me.

`yum update python*`
`yum install dnf-data dnf-plugins-core libdnf-devel libdnf python2-dnf-plugin-migrate dnf-automatic`

dnf is now working on a CentOS 7.5 box. Some packages might be unnecessary, but you have to try for yourself...

**Comment by xiaotianhu** [comment]
> > I mistook this for a different issue. It appears the root cause here is just that the dnf that lives in CentOS Extras is not compatible with anything older than EL 7.6.
> 
> After installing/updating some related packages, resolved the **"ImportError: No module named _conf"** issue for me.
> 
> `yum update python*`
> `yum install dnf-data dnf-plugins-core libdnf-devel libdnf python2-dnf-plugin-migrate dnf-automatic`
> 
> dnf is now working on a CentOS 7.5 box. Some packages might be unnecessary, but you have to try for yourself...

Thank you ,it works for me on centos 7.4.1708

**Comment by denis-khalturin-incountry** [comment]
@szsahin thank you :]

**Comment by vahidzolf** [comment]
@szsahin  thank you very much, you saved my life !!! :)
