### ISSUE TITLE
Create Actions for Stratagem - Manager Side

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#852]
Create Commands, Jobs, Steps for Stratagem on the manager side.

## ConfigureStratagem

   - Set the interval, 
   - set report duration 
   - set report duration active
   - set purge duration
   - set purge duration active

  - Creates a systemd timer on the manager that is responsible for calling the following command after either interval has elapsed (if the configuration is active for that particular command):
```
iml stratagem scan <FS_NAME> {report|purge}
```

## UnconfigureStratagem

  - Removes the systemd timer created during ConfigureStratagem.

## RunStratagem

  - Kicks off a run

  - Sends info to each MDS

  - Waits for all results

  - Aggregates results

  - Ingests Metrics

  - Sends relevant results to client to run actions.

  - Reports back results of client run.

**Comment by jgrund** [comment]
The `run_stratagem` call should take all of the config as arguments. The `configure_stratagem` call should only store those arguments so it can feed them into the IML CLI.

The CLI should be able to take all config and pass that into the `run_stratagem` call.
