### ISSUE TITLE
SSI: VolumeNode matching query does not exist

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#895]
In SSI testing, we see the following issue:

```
description: Update managed target mounts for target testfs-OST0000
class_name: UpdateManagedTargetMount
backtrace: Traceback (most recent call last):
  File "/usr/share/chroma-manager/chroma_core/services/job_scheduler/job_scheduler.py", line 326, in _run
    result = step.run(args)
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1443, in run
    expected_exception_classes=[VolumeNode.DoesNotExist],
  File "/usr/lib/python2.7/site-packages/iml_common/lib/util.py", line 220, in wait_for_result
    return lambda_expression()
  File "/usr/share/chroma-manager/chroma_core/models/target.py", line 1440, in <lambda>
    lambda: VolumeNode.objects.get(host=host, path=filesystem.mount_path(target.name)),
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: VolumeNode matching query does not exist.
```

Digging into this a bit, the `VolumeNode` *does* exist, but it has been marked deleted:

```
chroma=> select * from chroma_core_volumenode where host_id = 3 and id = 24;
 id | volume_id | host_id |                       path                       | storage_resource_id | primary | use | not_deleted
----+-----------+---------+--------------------------------------------------+---------------------+---------+-----+-------------
 24 |         3 |       3 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_target2 |                     | t       | t   |
```

Further the device-aggregator knows about this record when the bug occurs, which points to the bug being within the resource manager.

![Screen Shot 2019-04-26 at 4 15 54 PM](https://user-images.githubusercontent.com/458717/56834411-4e748c00-683f-11e9-8e86-42254b22cb5b.png)

**Comment by jgrund** [comment]
Temporary workaround if seen outside test:

```
systemctl restart iml-manager.target
```

Causes a re-read of devices

**Comment by AlexTalker** [comment]
@jgrund I am working on this problem right now.
On my installation it can be reproduced in monitoring-only mode.
Reason seems to be that anyhow, relation between `ManagedTargetMount` and `VolumeNode` and `Volume` and `ManagedTarget` are broken in following way:
1. There's an `ManagedTarget` which is valid and `not_deleted=True`
2. There's an `ManagedTargetMount` which is valid and `not_deleted=True`, associated with `ManagedTarget`
3. However, `VolumeNode` associated with this `ManagedTargetMount` is marked as deleted.
4. This `VolumeNode` references `Volume` marked as deleted which is referenced by `ManagedTarget`
4. But there's two not deleted `Volume` records, each per node, associated with device on which `ManagedTarget` is placed, so my guess is that somewhere change of relationship was broken.

So, my question is, where is to look for changes on `Volume`, `VolumeNode`, `ManagedTarget` and `ManagedTargetMount` in monitoring mode? Besides `update_scan.py`
Steps seems to be a part of management mode.

I'm running `IML` in Docker, so problem seems to be persistent in such environment, however, it is reproduced only by one node and not the other.

**Comment by AlexTalker** [comment]
I found out stable case to reproduce this(with `IML` server-side deployed in Docker):
1. Add nodes, scan for filesystems
2. Put a load on the test filesystem(I do use only one at the moment)
3. Targets distributed between nodes in `active-active` manner, i.e. some OST run on node A as primary and some on B
4. Reboot node B, while keeping the load
5. While rebooting, OST(in my case) `fail-over` to node A and restored there, connection to node B is lost
6. While on node A, statistics for `OSTs` successfully accepted
6. After booting up node B, connection is restored, `fall-back` to node B
7. Statistics for `OSTs` is not received anymore while they're on node B. Migrating an OST to A and back changes nothing - while on A, statistics received successfully.

Currently, I'm trying to discover life-cycle of involved models, this give me an idea why this case happened.

**Comment by AlexTalker** [comment]
@jgrund The problem seems to be symmetric. If I reboot the node A too, no stats come anymore.

**Comment by AlexTalker** [comment]
Deletion of `Volume` happens here https://github.com/whamcloud/integrated-manager-for-lustre/blob/master/chroma_core/services/plugin_runner/resource_manager.py#L799
It seems that after `fail-over` only `Volume` is marked as deleted and chain `ManagedTarget->ManagedTargetMount->VolumeNode->Volume` is valid and only `ManagedTarget->Volume` is broken. This can be fixed at the same place where relation `ManagedTarget->ManagedTargetMount` is updated I think.

**Comment by AlexTalker** [comment]
The problem seems to be that while deleting `Volume` when session is lost, after re-connection, `Volume` is re-created(as `VolumeNode` but not bind to models that utilize it correctly. A workaround might be looking up for deleted `VolumeNode` but this seems to be already done: https://github.com/whamcloud/integrated-manager-for-lustre/blob/5f8dcc3615388527c833df348617119352f51d07/chroma_core/services/plugin_runner/resource_manager.py#L544

**Comment by AlexTalker** [comment]
I finally made some changes to solve this problem. Will publish tomorrow.

**Comment by utopiabound** [comment]
https://build.whamcloud.com/job/integration-tests-shared-storage-configuration/1791
```
test_create_filesystem_with_failover_oss (tests.integration.shared_storage_configuration.test_managed_filesystem_with_failover.TestManagedFilesystemWithFailover) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 124, in test_create_filesystem_with_failover_oss
    filesystem_id, volumes_expected_hosts_in_normal_state = self._test_create_filesystem_with_failover()
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_managed_filesystem_with_failover.py", line 12, in _test_create_filesystem_with_failover
    filesystem_id = self.create_filesystem_standard(self.TEST_SERVERS)
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 397, in create_filesystem_standard
    "conf_params": {},
  File "/usr/share/chroma-manager/tests/integration/core/chroma_integration_testcase.py", line 465, in create_filesystem
    self.chroma_manager, command_id, verify_successful=verify_successful, timeout=LONG_TEST_TIMEOUT
  File "/usr/share/chroma-manager/tests/integration/core/api_testcase_with_test_reset.py", line 239, in wait_for_command
    self.assertFalse(command["errored"] or command["cancelled"], command)
```

VolumeNode for OST0001 (`/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_target4`) is deleted in database:
```
chroma=# select * from chroma_core_volumenode WHERE host_id = 4 and volume_id = 5;
 id | volume_id | host_id |                       path                       | storage_resource_id | primary | use | not_deleted 
----+-----------+---------+--------------------------------------------------+---------------------+---------+-----+-------------
 37 |         5 |       4 | /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_target4 |                     | t       | t   | 
```

**Comment by jgrund** [comment]
@utopiabound You should be able to correlate when the add and remove happened for this record by looking at the `plugin_runner.log`.

**Comment by jgrund** [comment]
Looking at this a bit more as I'm testing the rust device-scanner change and I've just hit this.

The `VolumeNode` is being removed by this method:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/f9789d42e3ebbafccdff33daa7abbd26f4e08eae/chroma_core/services/plugin_runner/resource_manager.py#L799-L806

This method appears to be called here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/f9789d42e3ebbafccdff33daa7abbd26f4e08eae/chroma_core/services/plugin_runner/resource_manager.py#L661-L664

**Comment by utopiabound** [comment]
It's actually being called here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/f9789d42e3ebbafccdff33daa7abbd26f4e08eae/chroma_core/services/plugin_runner/resource_manager.py#L711-L722

I got debugging logs:
```
[2019-05-23 17:34:03,605: DEBUG/storage_plugin] volume node 48 (126) usable False
[2019-05-23 17:34:03,605: INFO/storage_plugin] Removing VolumeNode 48
```

**Comment by jgrund** [comment]
At least one cause of this is a temporary mount that lustre creates when first creating the filesystem is picked up by IML and subsequently never removed.

This is a bug in `resource_manager.py` in that it should be cleared out once that temporary mount disappears.

To detect if this is the cause of appearances of this error you can execute a SQL query against the manager database.

```sql
select srr.storage_id_str, sq.storage_id_str
from chroma_core_storageresourcerecord srr,
(select srrp.to_storageresourcerecord_id, srr.storage_id_str
    from chroma_core_storageresourcerecord_parents srrp
    inner join chroma_core_storageresourcerecord srr
    on srrp.from_storageresourcerecord_id = srr.id) sq
where sq.to_storageresourcerecord_id = srr.id and srr.storage_id_str = 'TARGET_ID_STR_HERE';
```

`TARGET_ID_STR_HERE` can be found by querying `chroma_core_storageresourcerecord` and looking for the target that is not appearing under the `storage_id_str` column.

Executing the query for the run I found:

```sql
select srr.storage_id_str, sq.storage_id_str
from chroma_core_storageresourcerecord srr,
(select srrp.to_storageresourcerecord_id, srr.storage_id_str
    from chroma_core_storageresourcerecord_parents srrp
    inner join chroma_core_storageresourcerecord srr
    on srrp.from_storageresourcerecord_id = srr.id) sq
where sq.to_storageresourcerecord_id = srr.id and srr.storage_id_str = '["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_target4"]';
```

yields:

```
                    storage_id_str                    |   storage_id_str
------------------------------------------------------+--------------------
 ["/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_target4"] | ["/tmp/mnt9aU7P6"]
(1 row)
```

**Comment by AlexTalker** [comment]
@jgrund Is this reproduced in managed more or am I wrong?

**Comment by jgrund** [comment]
@AlexTalker I debugged it in managed mode. I haven't determined if this will occur in monitor mode but it seems reasonable that it could.

**Comment by AlexTalker** [comment]
@jgrund My case is that I have 3 nodes.
On one of them is the metadata and the other are DC which holds OSTs.
If I reboot one node with OSTs, then when it shut down, associated volumes and volume nodes are removed.
After booting, they get restored by do not get re-linked with mount points(which ain't got deleted).
Everything is in monitored mode.

**Comment by AlexTalker** [comment]
@jgrund If I keep everything in the DC, fix from my PR works. But on 3 it doesn't.
I can't swear if it has to do with metadata only but it is my current case.

**Comment by jgrund** [comment]
Taking another look at this for a feature being developed in monitored mode.

`ManagedTargetMount` does not update itself to mark `not_deleted` as null. Because of this, there are multiple `ManagedTargetMount` records that point to volumes, targets, and hosts that no longer exist.

To demonstrate:

```
chroma=> select count(*) from chroma_core_managedtargetmount where not_deleted = 't';
 count
-------
    75
```

```
chroma=> select count(*) from chroma_core_managedtargetmount as mtm 
inner join chroma_core_volumenode as vn 
on vn.id = mtm.volume_node_id  
and vn.not_deleted = 't' 
and mtm.not_deleted = 't';
 count
-------
    38
```

**Comment by jgrund** [comment]
> After booting, they get restored by do not get re-linked with mount points(which ain't got deleted).

@AlexTalker Are new mount points created?

**Comment by AlexTalker** [comment]
> 
> 
> > After booting, they get restored by do not get re-linked with mount points(which ain't got deleted).
> 
> @AlexTalker Are new mount points created?

Yeah, as far as I can remember it is so.

**Comment by jgrund** [comment]
I believe this is fixed, closing.
