### ISSUE TITLE
SSI: test_mcast_changes failover peer undetected 

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#931]
Seen in: https://build.whamcloud.com/job/integration-tests-shared-storage-configuration/1758/arch=x86_64,distro=el7,label=IML/consoleFull

In this test, two managed nodes are setup. A wait then occurs that there are no corosync related alerts. However, there is a persistent alert that each node does not have a failover peer:

<img width="755" alt="Screen Shot 2019-05-09 at 7 27 40 AM" src="https://user-images.githubusercontent.com/458717/57450295-181a1200-722c-11e9-84a5-fa05aa7018b5.png">

sos for each node:

[sosreport-vm5-2019-05-09-htwahqs.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3161868/sosreport-vm5-2019-05-09-htwahqs.tar.xz.zip)
[sosreport-vm6-2019-05-09-pvrxhxk.tar.xz.zip](https://github.com/whamcloud/integrated-manager-for-lustre/files/3161869/sosreport-vm6-2019-05-09-pvrxhxk.tar.xz.zip)

**Comment by jgrund** [comment]
@utopiabound Can you take a look at this one?

**Comment by utopiabound** [comment]
SSI Test failure in console:
```
test_mcast_changes (tests.integration.shared_storage_configuration.test_corosync.TestCorosync) ... FAIL
FAIL
Traceback (most recent call last):
  File "/usr/share/chroma-manager/tests/integration/shared_storage_configuration/test_corosync.py", line 210, in test_mcast_changes
    self.wait_for_assert(lambda: self.assertNoAlerts(self.server_configs[0]["corosync_configuration"]))
  File "/usr/share/chroma-manager/tests/integration/core/utility_testcase.py", line 193, in wait_for_assert
    "Timed out waiting for %s\nAssertion %s" % (inspect.getsource(lambda_expression), assertion),
AssertionError: Timed out waiting for         self.wait_for_assert(lambda: self.assertNoAlerts(self.server_configs[0]["corosync_configuration"]))

Assertion u'/api/corosync_configuration/1/' unexpectedly found in [u'/api/corosync_configuration/2/', u'/api/corosync_configuration/1/']
```

**Comment by utopiabound** [comment]
The issue is that vm5 and vm6 are configured for different mcast ports (when they should have found each other and configured correctly).

**Comment by jgrund** [comment]
I believe this is now fixed.
