### ISSUE TITLE
IML bug report: Docker stack race condition

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#945]
**Describe the bug**
To deploy the stack I use the following command per the iml instructions at https://whamcloud.github.io/Online-Help/docs/Install_Guide/ig_docker_stack.html:

```
docker stack deploy -c docker-compose.yml iml
```

All containers will load without error, but there are times in which I attempt to load the browser and receive a 502. At first, I thought there was a specific configuration issue, but I brought the stack down with:

```
docker stack rm iml
```
 
and then proceeded to bring the stack back up and everything was fine. Sometimes I have to do this 2 or 3 times before I can access the page. I believe a race condition of some sort is causing this.

**To Reproduce**
1. Follow the instructions at https://whamcloud.github.io/Online-Help/docs/Install_Guide/ig_docker_stack.html to deploy the docker stack.
2. Navigate the browser to `https://localhost:7443/ui/`

The web page may or may not load.

**Expected behavior**

All services should be running and should be started in the correct order every time. The webpage should then load without a 502 in every case that the stack is deployed.

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version  74.0.3729.157

### Version
What version of IML? 5.0 
What Operating System? Mac

**Comment by jgrund** [comment]
@johnsonw Can you please  post the cause of the 502?

Also, are you trying this on mac or linux?

**Comment by johnsonw** [comment]
I'm running this on docker for mac Version 2.0.0.3 (31259). I will follow up with more information shortly.

**Comment by jgrund** [comment]
If you can track down the 502 that will be very helpful.

**Comment by johnsonw** [comment]
For sure, working on reproducing now.

**Comment by johnsonw** [comment]
Still haven't been able to reproduce. As i'm working in docker I will keep an eye out for it. I wanted to create this ticket before I forgot so we are aware that it's happened a couple of times.

**Comment by jgrund** [comment]
@johnsonw does this still occur with the docker rework?

**Comment by johnsonw** [comment]
Haven't seen it in a while. However, I would like to keep this open just a bit longer while I integrate all the pieces if possible.
