### ISSUE TITLE
IML chroma-agent-daemon: InsecureRequestWarning

### ISSUE THREAD

**Issue by ahkumar** [whamcloud/integrated-manager-for-lustre#971]
**Describe the bug**
Disable insecure requests warning is not working. This statement "urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)" in /usr/lib/python2.7/site-packages/chroma_agent/agent_daemon.py has no affect and still outputs following warnings on all lustre servers repeatedly ever few seconds

Warning: 
oss002: May 31 14:43:30 oss002 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss002: May 31 14:43:30 oss002 chroma-agent-daemon: InsecureRequestWarning)

**To Reproduce**
1. Install IMLv5.0 on CentOS 7.5, with default python version 2.7.5
2. IML agents installed on CentOS 7.4, with python version 2.7.5 

**Screenshots**
pdsh>  grep InsecureRequestWarning /var/log/messages | tail -2
mds002: May 31 14:43:26 mds002 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
mds002: May 31 14:43:26 mds002 chroma-agent-daemon: InsecureRequestWarning)
mds001: May 31 14:43:28 mds001 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
mds001: May 31 14:43:28 mds001 chroma-agent-daemon: InsecureRequestWarning)
oss007: May 31 14:43:30 oss007 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss007: May 31 14:43:30 oss007 chroma-agent-daemon: InsecureRequestWarning)
oss006: May 31 14:43:27 oss006 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss006: May 31 14:43:27 oss006 chroma-agent-daemon: InsecureRequestWarning)
oss011: May 31 14:43:30 oss011 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss011: May 31 14:43:30 oss011 chroma-agent-daemon: InsecureRequestWarning)
oss005: May 31 14:43:29 oss005 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss005: May 31 14:43:29 oss005 chroma-agent-daemon: InsecureRequestWarning)
oss003: May 31 14:43:31 oss003 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss003: May 31 14:43:31 oss003 chroma-agent-daemon: InsecureRequestWarning)
oss001: May 31 14:43:25 oss001 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss001: May 31 14:43:25 oss001 chroma-agent-daemon: InsecureRequestWarning)
oss008: May 31 14:43:29 oss008 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss008: May 31 14:43:29 oss008 chroma-agent-daemon: InsecureRequestWarning)
oss012: May 31 14:43:30 oss012 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss012: May 31 14:43:30 oss012 chroma-agent-daemon: InsecureRequestWarning)
oss004: May 31 14:43:30 oss004 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss004: May 31 14:43:30 oss004 chroma-agent-daemon: InsecureRequestWarning)
oss002: May 31 14:43:30 oss002 chroma-agent-daemon: /usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
oss002: May 31 14:43:30 oss002 chroma-agent-daemon: InsecureRequestWarning)

### Version
What version of IML? v5.0
What Operating System? CentOS 
What Operating System version? v 7.5

Please let me know if you need additional information.  Thank you!!

**Comment by jgrund** [comment]
Hi @ahkumar, 

What versions of `python-requests` are available on the agents?

```yum info python-requests --show-duplicates```

**Comment by ahkumar** [comment]
HI @jgrund,

Here is what we have on the agents. Apparently our install picked up python-requests from our Cluster manager repository, below is the info:

Installed Packages
Name        : python-requests
Arch        : noarch
Version     : 2.10.0
Release     : 100031_cm8.1_f180c7427d
Size        : 369 k
Repo        : installed
From repo   : cm-rhel7-8.1-updates
Summary     : HTTP library, written in Python, for human beings
URL         : https://pypi.io/project/requests
License     : ASL 2.0
Description : Most existing Python modules for sending HTTP requests are extremely verbose and
            : cumbersome. Python’s built-in urllib2 module provides most of the HTTP
            : capabilities you should need, but the API is thoroughly broken. This library is
            : designed to make HTTP requests easy for developers.

Available Packages
Name        : python-requests
Arch        : noarch
Version     : 2.6.0
Release     : 1.el7_1
Size        : 94 k
Repo        : base/7/x86_64
Summary     : HTTP library, written in Python, for human beings
URL         : http://pypi.python.org/pypi/requests
License     : ASL 2.0
Description : Most existing Python modules for sending HTTP requests are extremely verbose and
            : cumbersome. Python’s built-in urllib2 module provides most of the HTTP
            : capabilities you should need, but the API is thoroughly broken. This library is
            : designed to make HTTP requests easy for developers.

**Comment by ahkumar** [comment]
Hi Joe,

Wanted to check few things: 
a) Does IML expect a cert other than self-signed certs? 
b) Does it expect Lustre servers to be able to communicate out to the internet? Ours don't. 

Thanks,
Amit

**Comment by johnsonw** [comment]
Hi @ahkumar,

> a) Does IML expect a cert other than self-signed certs? 
IML uses a self signed certificate for https connections. Certificate information on the agent nodes can be found under /etc/iml (for IML 5.0). 

> b) Does it expect Lustre servers to be able to communicate out to the internet? Ours don't.
Please see: https://whamcloud.github.io/Online-Help/docs/Install_Guide/Create_Offline_Repos_10_0.html

**Comment by jgrund** [comment]
Ah, you have a newer version of `python-requests` than what is available in base. If you can downgrade to 2.6 that should fix it. 

If you can't downgrade, let me know and I'll take a look at what's needed to disable warnings on the new version.

**Comment by jgrund** [comment]
To be clear, there is nothing that requires a self-signed cert throughout IML that I know of. It's more provided as a convenience if you don't want to provide your own signed certificates.

**Comment by ahkumar** [comment]
@jgrund, 
@johnsonw

Sorry for the delay. I was tied with other things. Thank you for your comments. 
Given this is production environment I don't want to downgrade a package installed from our provisioning system. I am not sure if it would cause any other issues. Is there a way you can help me with disabling warnings on the new version?

**Comment by ahkumar** [comment]
@jgrund

I happened to try downgrading on our test system and the warning disappears!! Unfortunately I am hesitant to downgrade it is production as it is I am troubleshooting data loss issues on production side in the last couple of days. Hence it wouldn't be an option to downgrade on production for the moment but the logs are filling up and any help in fixing this will be great help.

**Comment by jgrund** [comment]
Fixed in https://github.com/whamcloud/iml-agent/pull/104
