### ISSUE TITLE
How to change server profile

### ISSUE THREAD

**Issue by ldd91** [whamcloud/integrated-manager-for-lustre#973]
I deployed IML use docker stack,and I add server use manage mode,however the lustre-ldiskfs-zfs is  in  conflict with my server node's lustre-ldiskfs-dkms-2.12.2-1.el7.noarch ,I don't want to install lustre-ldiskfs-zfs,but i dont know how to change server profile. In docker i can't find chroma-config command

**Comment by jgrund** [comment]
Hi @ldd91, 

Do you already have Lustre installed on your storage servers?

If so, why not use the existing monitored mode profile instead of creating a new one?

**Comment by jgrund** [comment]
To be clear, monitored mode will work with existing Lustre installs (without any management capacity): https://whamcloud.github.io/Online-Help/docs/Detect_and_monitor_existing_LFS_7_0.html

**Comment by ldd91** [comment]
Yes I have Lustre installed on my storage servers,but  i want to implement failover of the cluster using Corosync and Pacemaker in manage mode

**Comment by ldd91** [comment]
How can  i remove lustre-ldiskfs-zf when using manage mode
