### ISSUE TITLE
IML create lustre failed due to corosync and pacemaker no start

### ISSUE THREAD

**Issue by ldd91** [whamcloud/integrated-manager-for-lustre#992]
**Describe the bug**
In my enviroment,I have a MDT and MGT and dont want to configure ha,and i have 2 OSS server,i use multipath,i want to configure failover in two OSS,I am coufused whether pcs must be installed in MDS Server if i only have one MDS.I read your artical https://whamcloud.github.io/Online-Help/docs/Contributor_Docs/cd_Installing_IML_On_Vagrant.html and i found " Managed storage servers must be physically configured for high-availability/server failover." What can i do if my MDS no configure failover
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

### Version
What version of IML?5.0.0
What Operating System?centos7
What Operating System version?

### sosreport

Attach any [`sosreport`s](https://whamcloud.github.io/Online-Help/docs/Install_Guide/ig_ch_15_appD_getting_help.html) for nodes relevant to this issue.

**Comment by jgrund** [comment]
Hi @ldd91,

We do not currently support managed installs without corosync / pacemaker.

While this is something we'd like to do someday, it's not likely we will be able to develop this in the short-term.

**Comment by ldd91** [comment]
Should every node join in the same pcs cluster?

**Comment by ldd91** [comment]
So now IML  only support at least two MDS server?If i only hava one MDS server can I install lustre throught  IML?

**Comment by ldd91** [comment]
@jgrund  If  I want to modify code,which part should i  change,Maybe I can contribute to this project
